### ISSUE TITLE
Add Python functions

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#100]
# Description

The functions in Python are presently not on Code Thesaurus. I would love to see this added.

# Requirements

* Copy `web/thesauruses/_meta/functions.json` to a `web/thesauruses/python/` directory
* Edit the functions.json file to accurately reflect Python and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://github.com/codethesaurus/docs/blob/main/docs/thesaurus/index.md](https://github.com/codethesaurus/docs/blob/main/docs/thesaurus/index.md) for information on more specifics of implementing this.

**Comment by pkdiv** [comment]
@geekygirlsarah  I would like to work on this issue

**Comment by geekygirlsarah** [comment]
Here you go. Have at it!
