### ISSUE TITLE
Add Scala functions

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#103]
# Description

The functions in Scala are presently not on Code Thesaurus. I would love to see this added.

# Requirements

* Copy `web/thesauruses/_meta/functions.json` to a `web/thesauruses/scala/` directory
* Edit the functions.json file to accurately reflect Scala and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on more specifics of implementing this.

**Comment by hypatian** [comment]
I'd like to take care of this. I'll have a question or two about how to approach something! (There are a few additional ways there can be different numbers of arguments in Scala.) But, I should be able to take care of the basics, anyway. :)

**Comment by geekygirlsarah** [comment]
Oh this would make me happy, both to have another thing and to see you involved!

A lot of things are answered in documentation (docs.codethesaur.us), but feel free to leave any questions or make a draft PR and we can work through them.

**Comment by geekygirlsarah** [comment]
Merged PR but didn't link this issue with it, so closing the issue now.
