### ISSUE TITLE
Add C# control structures

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#106]
# Description

The control structures (loops, ifs, etc.) in C# are presently not on Code Thesaurus. I would love to see this added.

# Requirements

* Copy `web/thesauruses/_meta/control_structures.json` to a `web/thesauruses/csharp/` directory
* Edit the control_structures.json file to accurately reflect C# and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on more specifics of implementing this.

**Comment by bmeverett** [comment]
Guess I revealed my hand a little 🙂 but I can try and take this one. PR coming soon!

**Comment by geekygirlsarah** [comment]
Cool! And I mean it works. I ask people to comment on an issue first so I can make sure two people don't try to do it at the same time and assign it to the first person. But hey, you get first dibs this time!
