### ISSUE TITLE
Add Go control structures

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#107]
# Description

The control structures (loops, ifs, etc.) in Go are presently not on Code Thesaurus. I would love to see this added.

# Requirements

* Copy `web/thesauruses/_meta/control_structures.json` to a `web/thesauruses/go/` directory
* Edit the control_structures.json file to accurately reflect Go and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on more specifics of implementing this.

**Comment by kellydanma** [comment]
👋 Just found this project and I think it's awesome! I can work on this issue.

**Comment by geekygirlsarah** [comment]
I'd say consider it yours but you already made a PR! I'll look it over probably tomorrow.

Thank you! 🎉

**Comment by kellydanma** [comment]
☝️ It's in draft right now because I haven't started working on it. I just copied the template over because I like to commit early. I'll remove the draft status once it's ready 😊

**Comment by geekygirlsarah** [comment]
Oh, I see! I know some people who do that. I saw the `WIP` but didn't see the draft status. That's fine!

Let me know if you have any questions. Also a minor update: You can delete all `name: "..."` fields in control_structures.json. They aren't needed anymore. There's also a new `comment: "..."` field you can add under each ID to add any details that aren't self-explanatory. Also docs.codethesaur.us has a Thesaurus Files section for modifying the file too.

Thanks!
