### ISSUE TITLE
Add Java control structures

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#108]
# Description

The control structures (loops, ifs, etc.) in Java are presently not on Code Thesaurus. I would love to see this added.

# Requirements

* Copy `web/thesauruses/_meta/control_structures.json` to a `web/thesauruses/java/` directory
* Edit the control_structures.json file to accurately reflect Java and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on more specifics of implementing this.

**Comment by enisaras** [comment]
I can actually help with this!

**Comment by geekygirlsarah** [comment]
Sweet! It's yours!

Feel free to check out the contributing guidelines, and ask if you have any questions. docs.codethesaur.us is the new site for documentation.
