### ISSUE TITLE
Add JavaScript control structures

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#109]
# Description

The control structures (loops, ifs, etc.) in JavaScript are presently not on Code Thesaurus. I would love to see this added.

# Requirements

* Copy `web/thesauruses/_meta/control_structures.json` to a `web/thesauruses/javascript/` directory
* Edit the control_structures.json file to accurately reflect JavaScript and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://github.com/codethesaurus/docs/blob/main/docs/thesaurus/index.md](https://github.com/codethesaurus/docs/blob/main/docs/thesaurus/index.md) for information on more specifics of implementing this.

**Comment by nicholasbus** [comment]
Hi, I would be interested in working on this issue. Thanks.

**Comment by geekygirlsarah** [comment]
Sure! I'll assign you to it. I'll keep you on for about a week and if I don't see anything after that I may remove you, but you can always reclaim this.

Check out the links in the issue for more info on the file structures and contribution process. And thanks in advance!
