### ISSUE TITLE
Add PHP control structures

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#111]
# Description

The control structures (loops, ifs, etc.) in PHP are presently not on Code Thesaurus. I would love to see this added.

# Requirements

* Copy `web/thesauruses/_meta/control_structures.json` to a `web/thesauruses/php/` directory
* Edit the control_structures.json file to accurately reflect PHP and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://github.com/codethesaurus/docs/blob/main/docs/thesaurus/index.md](https://github.com/codethesaurus/docs/blob/main/docs/thesaurus/index.md) for information on more specifics of implementing this.

**Comment by binarygary** [comment]
HI @geekygirlsarah I'd like to claim this issue

**Comment by geekygirlsarah** [comment]
Consider it yours, @binarygary ! And thanks!

Feel free to ask if you have any questions. The new link for docs are https://docs.codethesaur.us/
