### ISSUE TITLE
Add Scala control structures

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#115]
# Description

The control structures (loops, ifs, etc.) in Scala are presently not on Code Thesaurus. I would love to see this added.

# Requirements

* Copy `web/thesauruses/_meta/control_structures.json` to a `web/thesauruses/scala/` directory
* Edit the control_structures.json file to accurately reflect Scala and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on more specifics of implementing this.

**Comment by hypatian** [comment]
I'd like to take care of this!

**Comment by geekygirlsarah** [comment]
I'll give it to you too!
