### ISSUE TITLE
Add Haskell data types

### ISSUE THREAD

**Issue by cafce25** [codethesaurus/codethesaur.us#126]
# Description
The Haskell language is presently not on Code Thesaurus. I would love to see this added and the data types concept added to CT.

# Requirements
- Copy web/thesauruses/_meta/data_types.json to a web/thesauruses/haskell/ directory
- Edit the data_types.json file to accurately reflect Haskell and the latest major version of it.

# Additional Notes
Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/issues/CONTRIBUTING.md) for more information on how to contribute.

Check out https://github.com/codethesaurus/docs/blob/main/docs/thesaurus/index.md for information on more specifics of implementing this.

**Comment by cafce25** [comment]
Hey,
I'm currently working on this and decided to open the issue to avoid duplicating work and to be able to track questions/discussion on this later on.
@geekygirlsarah would you be so kind and assign me to this?

**Comment by geekygirlsarah** [comment]
@cafce25 There you go! Thanks for taking this on, and let me know if you have any questions.
