### ISSUE TITLE
Add Docker image

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#132]
# Description

Some people may not want to install Python and the stuff locally. We should offer a Docker image to run the whole system locally and allow people to work on the project without needing the manual install process.

# Requirements

* Add Dockerfile to build the system. (There may be a Django one out there already, but would need to have some of the extra dependencies added.)
* Update README with directions on how to run it

# Additional Notes

Take a look at https://docs.docker.com/compose/django/

Sarah can look into whether adding it to Docker Hub makes sense or not. If the Dockerfile is super simple, it may not really make sense.

**Comment by flour-ad** [comment]
Hello - I might try to do this!

**Comment by flour-ad** [comment]
So basically, the goal is to create a docker container, which when run, would serve the website? So the only step that user will have to take is to launch the docker container?

One more thing - in readme I see that PostgreSQL step is included only in instructions for Linux - I suggest adding it to the instructions for different operating systems as well, or deleting the instructions for Linux and highlighting that it is required for any OS at the beginning to avoid confusion. I think it may cause problems with setting up the virtual environment when postgresql is not already present.

**Comment by geekygirlsarah** [comment]
I'll pass it over to you then! Feel free to look over the contributor guidelines and ask me if you have any questions.

Postgres, at the moment, is _not_ needed. It's almost always attached to a Django install but I removed it as CT doesn't need it. I guess the person that last updated the README said they couldn't get it to run at all without installing Postgres due to Heroku's requirement for it for the package. I probably need to re-test it on all the installs. But I theorize it won't be needed for Docker and won't need the full Docker-compose setup either.

**Comment by flour-ad** [comment]
> I'll pass it over to you then! Feel free to look over the contributor guidelines and ask me if you have any questions.
> 
> Postgres, at the moment, is _not_ needed. It's almost always attached to a Django install but I removed it as CT doesn't need it. I guess the person that last updated the README said they couldn't get it to run at all without installing Postgres due to Heroku's requirement for it for the package. I probably need to re-test it on all the installs. But I theorize it won't be needed for Docker and won't need the full Docker-compose setup either.

Ok - I created a pull request. I think I did not link the issue number properly? if so, then let me know what I did wrong :>
