### ISSUE TITLE
Improve SEO and OpenGraph Info

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#135]
# Description

![image](https://user-images.githubusercontent.com/2601974/109406847-45c4d380-794a-11eb-8381-0410588a3c56.png)

When linking the site, it just copies the `<title>` and a one-line description. It would be nice to have it show the logo, a better description, and when on a reference/compare page, show the two languages.

# Requirements

* Add OpenGraph (i.e. `og:title` type tags) to make it appear when linked to give a better description of the page.
* Info should be on the home page, compare, and research pages. (Look through the templates to see what's there and where it could be added.)
* Add a unit test for this as well

# Additional Notes

There are plugins for the browser like [Open Graph Preview](https://addons.mozilla.org/en-US/firefox/addon/open-graph-preview-and-debug/) for Firefox and probably similar for Chrome. They will show you what the page's info looks like, and how it might look when pasted on Twitter/Facebook/Slack/Discord/etc.

**Comment by unnati914** [comment]
could i work on this?

**Comment by geekygirlsarah** [comment]
Yeah, have at it! If you have any questions, let me know!

**Comment by lukeberry99** [comment]
Is this still being worked on, or is it up for grabs?

**Comment by geekygirlsarah** [comment]
I think since I haven't seen any work fron @unnati914 in over a month, I'm willing to reassign it.

Let me know if you have any questions @lukeberry99  or if you need any help!

**Comment by lukeberry99** [comment]
@geekygirlsarah what image (if any) would you like opengraph to render?

**Comment by geekygirlsarah** [comment]
Good question! On the main branch, I just added web/static/images/ and two images in there. You can take one of those (the SVG or PNG) to use as a logo. (I just never added it to the site yet)

**Comment by lukeberry99** [comment]
@geekygirlsarah the issue calls for unit test for this feature, I can't find a way with the current testing set up of this project to check what meta tags are being rendered within the view and it feels out of the scope for this pull request to implement additional testing functionality. 

Are you comfortable with my omitting unit tests from this PR, and creating an issue for additional testing tools?

**Comment by lukeberry99** [comment]
I've created the PR as a draft for now until I hear back regarding the above.

**Comment by geekygirlsarah** [comment]
That's fine. it's an awkward thing to test, so I'm ok with leaving it out for now.
