### ISSUE TITLE
Redirect from HTTP to HTTPS

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#136]
# Expected Behavior

Going to codethesaur.us shoudl take you to the https site by default.

# Actual Behavior

Going to codethesaur.us may take you to http:// rather than https://. 

# Steps to Reproduce the Problem

1. Type in the URL directly with no http/https on it.

# Specifications

This happens on Firefox and Chrome.

**Comment by vaibhvshrma** [comment]
Hey @geekygirlsarah, would like to pick this up. The approach here would be to redirect all http requests to https except when working with settings.DEBUG set to True. Does this sound okay?

**Comment by geekygirlsarah** [comment]
Yeah, sounds good to me. Probably safe to assume it's debug mode unless set to production mode on the server. (or if I need to do something to change that, let me know)

**Comment by vaibhvshrma** [comment]
@geekygirlsarah Alright, thanks for confirming! 
Right now, debug is controlled through a env variable `SYSTEM_ENV`. So yes it is debug in all other than staging or production it seems.
Based on its value, here is the condition in settings.py

```
if SYSTEM_ENV == 'PRODUCTION' or SYSTEM_ENV == 'STAGING':  
    DEBUG = False  
else:  
    DEBUG = True
```
This is also where you will have to change the config if you are defining production env in a different way.
