### ISSUE TITLE
Add "Report a Language Issue" as issue creation template

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#139]
# Description

If there's something wrong with a language data set, it's not really a "bug" as much as just "incorrect information." It leaves the template to fill it out kind of weird. This is to revise that template to be a bit more specific to that.

# Requirements

* Add a new template in `.github/ISSUE_TEMPLATE` directory with this
* Have it include prompts like language, language structure, and specific field(s) that are wrong
* Have it optionally say what the correct info is
* Have it also mention if someone also wants to PR it, they need to also leave a comment so it's assigned to them.
* Include people requesting a new language set as well (see below)

# Additional Notes

There should be a place for a person to request a new language structure set too. I'll leave it up to you if this should be in the same template or in a separate template. (Either way, I think both should be included in this PR whether it's 1 or 2 templates.)

See https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository for GitHub's documentation on this.

**Comment by enisaras** [comment]
I can help with this issue.

**Comment by geekygirlsarah** [comment]
Consider it yours! And feel free to ask if you have any questions.
