### ISSUE TITLE
Remove hard coding of language concepts

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#144]
# Description

On `web/templates/index.html`, The dropdown for language concepts is hard-coded. It should be pulled in from meta_info.json.

# Requirements

* Remove commented out <option> elements
* Use similar loop for pulling in languages to pull in language concepts

**Comment by mat888** [comment]
It looks  like the file has the loop in it now, and no html comments exist. Am I misunderstanding or is it possible this issue has been resolved?

**Comment by geekygirlsarah** [comment]
I think you're right. I might have looked at my personal repo before pulling in changes.

I'll close this...

Thanks!
