### ISSUE TITLE
Bug on CI on folder path

### ISSUE THREAD

**Issue by juancarlospaco** [codethesaurus/codethesaur.us#149]
![bug](https://user-images.githubusercontent.com/1189414/109437257-a31c5b80-7a02-11eb-8e05-83d06734595e.png)

CI is searching for folders at:

`'web/thesauruses/Python/data_types.json'`

But that folder does not exist, it is:

`'web/thesauruses/python/data_types.json'`

Same for the other langs.
is Blocking https://github.com/codethesaurus/codethesaur.us/pull/148

I recommend using lowercase everywhere. :slightly_smiling_face:

**Comment by geekygirlsarah** [comment]
I think this is related to issue #152 and I'll take it on since I think my fix will resolve both.

**Comment by geekygirlsarah** [comment]
This should be fixed from PR #154, so I'm going to go ahead and close this.

Thank you for reporting it!
