### ISSUE TITLE
Test directory letter case does not match actual

### ISSUE THREAD

**Issue by mat888** [codethesaurus/codethesaur.us#151]
# Expected Behavior
Test should have looked in:
`web/thesauruses/python/`

# Actual Behavior
Test looked in:
`web/thesauruses/Python/`

# Steps to Reproduce the Problem

1. Submit Pull Request
2. Examine automated test output

The relevant output:

`FileNotFoundError: [Errno 2] No such file or directory: 'web/thesauruses/Python/data_types.json'

This directory does not exist like this in the main branch, again, the 'p' in "python" is actually lowercase.

Relevant to these PR's:
https://github.com/codethesaurus/codethesaur.us/pull/129
https://github.com/codethesaurus/codethesaur.us/pull/131
https://github.com/codethesaurus/codethesaur.us/pull/148/
https://github.com/codethesaurus/codethesaur.us/pull/150

Not exactly sure if case sensitivity matters, but its probably better the test reflects the actual directory structure in any case, and unlikely that each of these PR's inadvertently made a mistake that led to this same failure.

**Comment by geekygirlsarah** [comment]
Yeah I think that's the same problem that came up for issue #149. I'm closing this as it's a duplicate for that, but I'm going to try to fix the test tomorrow. Since it's ran in a Linux environment, capitalization does matter, so it's an issue.

Thanks for noticing this and what the issue was!!

**Comment by mat888** [comment]
NP, sorry for the dupe.

**Comment by geekygirlsarah** [comment]
Totally fine! It's helpful to have the list of PRs all in one place as well as confirmation it's not a fluke!
