### ISSUE TITLE
Test fails to find `/reference/ directory.

### ISSUE THREAD

**Issue by mat888** [codethesaurus/codethesaur.us#152]
# Expected Behavior

Test to find `/reference` directory.

# Actual Behavior

Test fails because it cannot find the `/reference` directory on the website/server. Even on a clean clone with no changes this test will fail, as does the website to find it. 

# Steps to Reproduce the Problem

1. Fix uppercase directory test bug [issue 149](https://github.com/codethesaurus/codethesaur.us/issues/149) ([PR](https://github.com/codethesaurus/codethesaur.us/pull/150) to fix that)
2. Run `python manage.py tests`

# Specifications

* codethesaur.us Version: 
* Python Version: 3.9

**Comment by geekygirlsarah** [comment]
I know what the cause of this is and I'll take it on.

**Comment by geekygirlsarah** [comment]
PR #154 should have closed this.
