### ISSUE TITLE
Empty box in the bottom of every thesaurus 

### ISSUE THREAD

**Issue by enisaras** [codethesaurus/codethesaur.us#155]
# Expected Behavior
There should not be an empty box in the bottom of every thesaurus, this box should either contain something or be removed.
# Actual Behavior
There is an empty box in the bottom of every thesaurus in the website, usually to the left of the prompt that calls for people to submit correct information.
# Steps to Reproduce the Problem

1. Go to this link: [Java vs. C++ data types](http://codethesaur.us/compare/?concept=data_types&lang1=java&lang2=cplusplus)
2. Scroll to the bottom of the page

# Specifications
I know this is mostly a nitpick issue and doesn't bother everyone but I think it doesn't look that great. I think we could put a different prompt there or just simply remove it.
* codethesaur.us Version: Latest
* Python Version:3.9

**Comment by geekygirlsarah** [comment]
Oh, you know I think I knew it was there but never really paid attention to it. It's a valid point though!

Thanks for reporting this!

**Comment by 3dvkr** [comment]
Hi, I'd like to look into this issue 👋. Should there be a different prompt in that first box, or is it better for that last line to only keep the last two boxes with the links?

**Comment by geekygirlsarah** [comment]
Alright, I'll pass it to you!

I can't think of what should go in there so it can stay empty/non-existent. You can probably just turn borders off on it or something similar so it doesn't show up.
