### ISSUE TITLE
Python code is indentation sensitive and should be shown with indentation

### ISSUE THREAD

**Issue by cafce25** [codethesaurus/codethesaur.us#156]
I suspect this is a general issue with the front-end and applies to other indentation sensitive languages too. 

# Expected Behavior
The control structures for python are displayed with correct indentation like so:
```python
if condition:
    statements
```
# Actual Behavior
The indentation gets stripped out by the front-end resulting in
```
if condition:
statements
```

# Steps to Reproduce the Problem
1. Visit [The control structures page for python](https://codethesaur.us/reference/?concept=control_structures&lang=python)

# Specifications
* codethesaur.us Version: git sha 'dae0b20'
* Python Version: 3.9.2

**Comment by geekygirlsarah** [comment]
Ah, good catch. And you're right, it's a front end bug.

**Comment by enisaras** [comment]
To add to this I think all languages should be shown with indentation in control structures like the one in python since(for most languages) the recommended coding style is to indent the statements in the code block after the condition is declared for readability.

**Comment by geekygirlsarah** [comment]
This has two parts:
- The site may not show spaces/tabs if they exist in JSON files
- The language files may not have spaces/tabs in them if the language requires it

The former seems in line with this ticket. The latter is more specific to any particular language and requires a bit more manual intervention and may affect several. At some point I'll probably go through and clean up some of the JSON files anyway.
