### ISSUE TITLE
Python functions JSON template is wrong

### ISSUE THREAD

**Issue by enisaras** [codethesaurus/codethesaur.us#159]
# Expected Behavior
The python functions are implemented in codethesaurus so it should display a page of info if we go to python functions on the website. 

# Actual Behavior
If we go to python functions the website returns that it has not been implemented yet.

# Steps to Reproduce the Problem

1. [Go on this link](http://codethesaur.us/reference/?concept=functions&lang=python)
1. See that it doesn't display information.
1. 

# Additional Info
This happens because the json file for python functions is written wrong. There are unescaped newlines but json format does not allow them, only escaped ones(\n).

**Comment by enisaras** [comment]
I realized this bug when I was working on adding the linter over in my fork, I can work on this issue.

**Comment by geekygirlsarah** [comment]
Sure! It's yours.

(You sure you're not taking on too many issues here?)

**Comment by cafce25** [comment]
Like with #160 fixed it before I realized this was already assigned to @enisaras, let me know if any of those fixes conflict with work you have already done.

**Comment by enisaras** [comment]
Hey @geekygirlsarah Im kinda busy atm, if this can wait until after my finals(May 11th) Ill be more than happy to redo this and add your suggestions, if not you can assign it to someone else.
