### ISSUE TITLE
Control Structures C++ JSON file is wrong

### ISSUE THREAD

**Issue by enisaras** [codethesaurus/codethesaur.us#160]
# Expected Behavior
The C++ control structures are implemented in codethesaurus so it should display a page of info if we go to python functions on the website. 

# Actual Behavior
If we go to C++ control structures on the website returns that it has not been implemented yet.

# Steps to Reproduce the Problem

1. [Go on this link](http://codethesaur.us/reference/?concept=control_structures&lang=cplusplus)
1. See that it doesn't display information.
1. 

# Additional Info
This happens because the json file for C++ control structures is written wrong. There are unescaped newlines but json format does not allow them, only escaped ones(\n).

**Comment by enisaras** [comment]
I also realized this issue when I was working on adding the linter, I would like to work on it.

**Comment by geekygirlsarah** [comment]
Sure! It's yours.

(You sure you're not taking on too many issues here?)

**Comment by cafce25** [comment]
I did not realize this issue existed and was assigned to you @enisaras if you already have a fix for the c++ file and it conflicts with #197 I can remove the offending files.
