### ISSUE TITLE
Add a highlighting library for formatting/coloring

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#170]
# Description

This would add a code highlighting library so that code objects would be formatted and colored according to the style of the language displayed.

# Requirements

1. Research Prism.js, Highlight.js, or Pygments to see what might be the best scenario to support the most languages and easily integrate into CT.
1. Add the library to the main header/footer templates, then in appropriate compare/reference templates.
1. Ensure the column of that language is formatted correctly for that particular language. (This may mean passing over another variable to the template from the controller/view if need be.)

# Additional Notes

If you think there's a better syntax highlighter than these, feel free to drop a comment and I'd be happy to look it over.

**Comment by LuisCardosoOliveira** [comment]
Hey @geekygirlsarah, saw your issue while surfing around github. I would love to help you with that 😄

**Comment by cafce25** [comment]
I'm currently looking into this. Is there a particular reason to do this client side with javascript? Cause python provides a great syntax highligting library with `pygments`. That way syntax highligting would also be available even if the user turns off javascript.

**Comment by geekygirlsarah** [comment]
!!! I had no clue Python had one of these!

No, I'm not really swayed one way or another. If you want to go the Pygments route, I think I'd be fine with that.
