### ISSUE TITLE
Add more useful unit tests

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#172]
# Description

There's a few unit tests there, which do a bare minimum of ensuring site functionality. This would be to test a wider range of cases of working and non-working items.

# Requirements

* Include testing all the pages
* Should test working systems for compare/reference
* Should test picking languages or concepts that don't exist
* Probably should test JSON files that don't work right or aren't structured right

# Additional Notes

Add any additional ones that make sense and are expected to help ensure site reliability.

**Comment by pselle** [comment]
Deferring JSON work to using a linter, linked PR includes unit tests
