### ISSUE TITLE
Function structures: Add keyword arguments

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#184]
# Description

Some languages like Ruby have the ability to add parameters out of order or as keywords.

As normal parameters:
`def function_name(param1, param2)   ...`
As keyword parameters:
`def function_name(name_of_param: param2, other_name: param1) ...`

# Requirements

Add these as additional IDs to the functions.json file

**Comment by lsparlin** [comment]
👋 Hi! I'd like to work on this

**Comment by geekygirlsarah** [comment]
Hey @lsparlin, yeah, I'll assign to you. If you have any questions, let me know. (A lot about adding stuff is in documentation.)

For this, just edit the `web/thesauruses/_meta/functions.json` file, don't modify any for any languages. (You can do that if you want, just make it a separate PR)

**Comment by lsparlin** [comment]
Thanks @geekygirlsarah. Really cool project you have here!!

**Comment by geekygirlsarah** [comment]
> 
> 
> Thanks @geekygirlsarah. Really cool project you have here!!

Thank you! 😁 I appreciate that! I basically tell people it's the tool I've needed for like the last 6 years and never could find anywhere, so I finally got myself to make it over the last 2-3 Hacktoberfests.
