### ISSUE TITLE
Add All Contributors to track contributions 

### ISSUE THREAD

**Issue by bmeverett** [codethesaurus/codethesaur.us#193]
# Description

Easily track contributions with a Github bot on the repo. You can define what people work on and can see what everyone contributed to in the README. You can also possible link to the README on the site, or even show the table somehow

# Requirements

Follow the instructions to install the bot for this repo https://allcontributors.org/docs/en/bot/installation
Once the bot is setup, you can tag the bot on PRs and add people for different contributions like code, docs, etc. 

# Additional Notes
You can see what the contributors table looks like [here](https://github.com/all-contributors/all-contributors)
[All Contributors site](https://allcontributors.org/)

**Comment by aryasoni98** [comment]
Could i work on this?

**Comment by geekygirlsarah** [comment]
I've been rolling this around in my head as I like the idea of this, but I'd probably rather have it as a page on the site, not adding to the readme (or other file). I'm looking into options on this and seeing what I might want. I do appreciate the suggestion @bmeverett and the willingness to work on it @aryasoni98! I'll comment back here when I figure out what I'm thinking.
