### ISSUE TITLE
Error handling in control structures

### ISSUE THREAD

**Issue by cafce25** [codethesaurus/codethesaur.us#194]
# Description

There is currently no category for error handling in the control structures files.

# Requirements

- Add a category for error control flow to [control_structures.json](https://github.com/codethesaurus/codethesaur.us/blob/8720117564bebcb6ce8067123423d235463f774c/web/thesauruses/_meta/control_structures.json)
- Add ids for typically found structures: `try, catch, finally`, `defer`, etc

**Comment by geekygirlsarah** [comment]
Good add! I thought about making error handling its own section, but it could go in control structures too.

**Comment by cafce25** [comment]
Closing since this is it's own structure now.

**Comment by geekygirlsarah** [comment]
Ahhh, good catch. Thanks!
