### ISSUE TITLE
Syntax highlighting does not work for PHP.

### ISSUE THREAD

**Issue by cafce25** [codethesaurus/codethesaur.us#206]
# Expected Behavior

PHP code should get the same syntax highlight treatment as other languages.

# Actual Behavior

All PHP code is just highlighted with the class 'x'

# Steps to Reproduce the Problem

1. Visit any page that includes PHP (i.e. [control structure reference](http://codethesaur.us/reference/?lang=php&concept=control_structures))
1. Observe there is no syntax highlighting and every bit of code is wrapped in `<span class="x"></span>`

# Additional Info

A quick search for the issue reveals that PHP syntax highlighting requires `<?php` by default.
[The pygment documentation](https://pygments.org/docs/lexers/?highlight=php#module-pygments.lexers.php) suggests we can pass in `startinline=True` to make the PHP lexer start with code directly without requiring the start tag.

**Comment by geekygirlsarah** [comment]
Oh good catch! Thanks!
