### ISSUE TITLE
The contributing links on the bottom don't work

### ISSUE THREAD

**Issue by cafce25** [codethesaurus/codethesaur.us#207]
# Expected Behavior

The links at the bottom should link to the relevant json files.

# Actual Behavior

The links result in a 404 error page.

# Steps to Reproduce the Problem

1. Visit [a compare](http://codethesaur.us/compare/?concept=control_structures&lang1=python&lang2=haskell) or [a reference](https://codethesaur.us/reference/?concept=control_structures&lang=ada) page.
1. Scroll down to the contributing links and click on them.
1. End up at a github 404 page.

# Additional Info

It looks like the links are missing the concept page parts ('control_structures', 'functions', ...)

**Comment by cafce25** [comment]
It looks like `concept_id` used in the templates got renamed to just `id` we probably just need to replace the former with the latter in the [reference template](https://github.com/codethesaurus/codethesaur.us/blob/b23932b29bfa310fcca8af4ecebb1582d8bc0582/web/templates/reference.html#L54) and the [compare template](https://github.com/codethesaurus/codethesaur.us/blob/b23932b29bfa310fcca8af4ecebb1582d8bc0582/web/templates/compare.html#L61)

**Comment by wilkie** [comment]
Fixed in #227 .
