### ISSUE TITLE
Remove need for Categories block from language JSON files

### ISSUE THREAD

**Issue by cafce25** [codethesaurus/codethesaur.us#208]
# Description
The categories section in all the languages files look exactly like the ones in the respective _meta files (apart from not being up to date). I think it would make the language files easier to write & look cleaner if we just dropped this duplicate information.

# Additional Info
Now with #204 the need to signify concepts that are not implemented for a language is handled in the respective concept blocks.

**Comment by geekygirlsarah** [comment]
Yeah, I agree. I was thinking about this the other day. At some point, the docs site needs to be updated to reflect no "name", adding "not implemented", adding "comment", and to remove categories.

**Comment by cafce25** [comment]
I'm gonna pick this up if it's ok.
Some additional thoughts I had in the meantime:
1. The `_meta` and `language` files are drifting apart more and more. Maybe we should add `_template` files to copy which more closely resemble the structure of the language files.
2. The `_meta` files then could be simplified to only include `category`, `concept.id`s and `concept.name`s
3. Every file contains the key `filename` (`lists.json` has a `lists` ...) to have a single source of truth we could rename that to `concepts`

**Comment by geekygirlsarah** [comment]
The original plan wasn't to have meta and language files match exactly, but they were kind of an easy way to start with a template of a new language file. So I kept them kind of the same. One thought I had was maybe having a Django command copy and remove the extra parts for you, but that's harder over Docker. I had thought about a templates directory (I think I was thinking `_new` but `_template` probably makes more sense) that could work, but that's now maintaining three separate kinds of files (also whatever corrections or additions to the meta language file need to be duplicated in _template). It could work, but makes it another point where stuff can stray apart that I'm not a fan of.

The `concept_id` to `concepts` idea works, and I pondered it. One of the things I was trying to do was ensure files were identifiable even if they got renamed, moved, etc. by accident. Without the language/language ID/version number at the top, and without that concept ID, nothing really identifies the file outside of the filename, and so there's no guarantee there. But that language/meta block at the top isn't used anywhere. So I haven't thought out a good solution to not needing them but have seen I've mixed up files before, so I'd like to think I'm not the only one that might do this. But I'd be open to thoughts on this.

**Comment by cafce25** [comment]
For leaving the info in I think I'd prefer to put it in `meta` maybe as `structure`-field then. We could treat that section as sort of comment for people. In that case I would point out in the docs that the info that the system uses is the directory/filename and the `meta` section is there to help us.

**Comment by geekygirlsarah** [comment]
> For leaving the info in I think I'd prefer to put it in `meta` maybe as `structure`-field then. We could treat that section as sort of comment for people. In that case I would point out in the docs that the info that the system uses is the directory/filename and the `meta` section is there to help us.

That works, though "structure" is also something I've used to refer to concepts. 

(I think ultimately I'd like to switch from structure > category > concept to category > subcategory > concept possibly, but I haven't though that through as much. I'm starting to think I should just get you on a call and think things out, lol)
