### ISSUE TITLE
Feature: Work on home page design

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#21]
**Description:**
The home page of CT has a basic Bootstrap setup but it's not really well done. It's technically "responsive" but isn't really set up for great mobile viewing. I'd like to see this either redesigned entirely or have some of the issues fixed so it works a little better.

**Requirements:**:
* Has the main navigation bar have both a Home and About page. This menu will need to grow as time goes on.
* It has a similar introductory description paragraph talking about the project
* Has two sections for the "Learn a Language" and "See a Reference Sheet", both with drop down boxes like they have now.
* A footer at the bottom with a link to the project itself. (This can stay the same as it is now.)
* It should stay fairly simple but if you want to add a front-end framework, discuss it below and why you think it would be good to have it. 

**Notes:**
Files to modify are in `web/templates` or `web/static`.

**Claiming This Issue:**
* Please leave a comment below indicating your interest. I can then assign it to you.
* If I don't see an update (comment, code, or PR), then I'll take your name off.
* You would always be welcome to reclaim it again.
* If you can't work on it, either leave a comment or remove yourself from the issue.
* If you have questions, please let me know!

**Comment by BergFulton** [comment]
This seems like something I can work on 🤩

**Comment by geekygirlsarah** [comment]
It's yours @BergFulton ! Let me know if you have any questions or want to work together on it.

If there's no updates in about a week (so Oct 7), I might take you off the issue.

**Comment by geekygirlsarah** [comment]
@BergFulton It's been about a week, so I'm going to go ahead and take you off of this so maybe others could contribute. If you want to reclaim this, let me know!

**Comment by LakshmiTejaP** [comment]
Can I work on this issue? Please let me know.

**Comment by geekygirlsarah** [comment]
Sure! You can have this issue, @LakshmiTejaP! I'll leave you on for a week, and if I don't see any updates, I'll take you off. If that happens, you can always claim it again.

Let me know if you have any questions!

**Comment by LakshmiTejaP** [comment]
@geekygirlsarah  I'm sorry. I have exams this week. Can't work for this. You can assign someone else.

**Comment by geekygirlsarah** [comment]
That's fine. Thanks for letting me know @LakshmiTejaP !

**Comment by pattimcletchie** [comment]
@geekygirlsarah I'd love to take this on if it's available. :)

**Comment by geekygirlsarah** [comment]
@pattimcletchie Sure, I'll give it to you! I'll leave you on for a week. If I don't see any updates, I'll take you off. If that happens, you can always claim it again.

Let me know if you have any questions!

**Comment by pattimcletchie** [comment]
@geekygirlsarah I am having an issue installing python. Are you able to assist me?

**Comment by geekygirlsarah** [comment]
The README was updated today for all the operating systems, so if you don't have the latest version you can look at that.

Otherwise, I can try. What's your OS?

**Comment by pattimcletchie** [comment]
Let me pull the latest. I am running Mac OS. @geekygirlsarah

**Comment by geekygirlsarah** [comment]
How's it going? Anything I can do to help, @pattimcletchie ?

**Comment by pattimcletchie** [comment]
@geekygirlsarah I pulled down the latest `README` and I was able to get localhost up and running. I should be good to go :) Thank you for your help.

**Comment by geekygirlsarah** [comment]
Sweet! Ping me here or twitter (same username) or email if you need anything!

**Comment by pattimcletchie** [comment]
@geekygirlsarah  I noticed that your app.scss file is different than your app.css file and when making changes to app.scss it doesn't compile and then update your app.css file (I assume you aren't using anything like webpack since it's python?). Are you utilizing SCSS or no?

**Comment by geekygirlsarah** [comment]
Oops... so those are residuals left over from the old Laravel (PHP) framework it used to be in. There's no Vue or SCSS/Less/etc. being used. You can effectively delete those. (not app.css, that IS getting used)

You could also re-pull master as I removed those.

Sorry about the confusion! That's what I get for trying to rewrite the framework from one language to another....

**Comment by pattimcletchie** [comment]
No worries! I will remove the files with my checkin.

**Comment by geekygirlsarah** [comment]
I like it! I might tweak the colors a bit but appreciate the work! I'll merge it in.

Have a lovely weekend!
