### ISSUE TITLE
Add concept descriptions to _meta files

### ISSUE THREAD

**Issue by hypatian** [codethesaurus/codethesaur.us#212]
# Description

Add an English (and hopefully some day localized) description of each concept, so that it's clear from something other than examination of multiple language files what the concept is meant to embody. This is especially important when a concept hasn't been added yet for any programming languages, but also if different programming languages' examples seem to conflict with each other.

# Requirements

For basic utility, this feature needs each concept simply needs to have a description. It may be sufficient to include this in the documentation to begin with, although that makes it easier for new concepts to be added without adding descriptions for them.

For a full implementation, the descriptions should be presented (although perhaps not by default) in the website as a reference.

# Additional Notes

Longer term, this is something that absolutely should be localized for the website, or translated in the documentation.

**Comment by geekygirlsarah** [comment]
I'm adding "help wanted" to this because I'd love the help, but I also imagine this needs to be thought through and discussed.

(Also I'd love to add internationalization at some point. I've been trying to keep that in mind as I'm adding various pieces to this project.)

**Comment by geekygirlsarah** [comment]
This was fixed a few months ago in #241, so I'm closing it. 

Thanks @hypatian for adding this!
