### ISSUE TITLE
Add Markdown support for language file comments

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#213]
# Description

Some people have started adding Markdown-style notations to the comments property in language files. 

# Requirements

1. Use a Python or JavaScript library to render Markdown on comments
2. Display them correctly in the templates (compare and reference)
3. Test it to make sure it works

# Additional Notes

If there's several options that are found for this, feel free to ask about them in the thread and we can discuss comparing them.

**Comment by aitorres** [comment]
Hello! I'm interested in working on this issue :-)

**Comment by geekygirlsarah** [comment]
Sure! Feel free to read over the documentation, and ask me if you have any questions!
