### ISSUE TITLE
Add signed vs unsigned numerical types

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#219]
# Missing Concepts

For the meta structure data types file:

For numerical data types, ints, floats, etc. can often be separated by signed or unsigned types. They should be split out.

**Comment by juancarlospaco** [comment]
I dont know if "Subranges" (aka "Ranges") should be considered in the future, Nim has a type you can use for ordinal data,
and the compiler makes sure it cant take higher nor lower values than the type allows, examples:
https://play.nim-lang.org/#ix=3n0x
