### ISSUE TITLE
Feature: Work on "Learn a Language" and "Reference Sheet" pages

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#22]
**Description**:
The Learn a Language and Reference Sheet pages of CT have a basic Bootstrap setups but it's not really well done. It's technically "responsive" but doesn't format the pages in a way that makes it easy to read or keeps the data together correctly when viewed on a mobile device. I'd like to see this redesigned entirely or fixed in a way that resolves these issues.

**Requirements:**
* Borrows navigation bar formatting from the home page
* Would display language data in a table-like way to make it easy to compare items ("Learn A Language" page) or easily look at items ("Reference Sheet" page)
* Should appear in table-like form for desktop viewing
* Should have data grouped together in the best format for mobile viewing
* Footer at the bottom of the page should match the home page.
* It should stay fairly simple but if you want to add a front-end framework, discuss it below and why you think it would be good to have it.

**Notes:**
Files to modify are in `web/templates` or `web/static`.

**Claiming This Issue:**
* Please leave a comment below indicating your interest. I can then assign it to you.
* If I don't see an update (comment, code, or PR), then I'll take your name off.
* You would always be welcome to reclaim it again.
* If you can't work on it, either leave a comment or remove yourself from the issue.
* If you have questions, please let me know!

**Comment by BetweenTwoLights** [comment]
I would like to give this a go.  May I pick up this issues?

**Comment by geekygirlsarah** [comment]
Yes! It's yours. If I don't see any activity in a week, I'll remove you so others can work on it. (You can always reclaim it again.)

And let me know if you have any questions!

**Comment by geekygirlsarah** [comment]
Fixed with 9cbb6c3 and 64f3a2f .
