### ISSUE TITLE
Add Perl language

### ISSUE THREAD

**Issue by CandyAngel** [codethesaurus/codethesaur.us#225]
Heyas! Rachel Singh linked me to this project and I noticed there is no Perl!
I would like to fix this clearly egregious oversight :P

In all seriousness, I would like to contribute/claim a "Perl" side of this project.
I really like "Rosetta Stone" type things as I often code in languages I don't know, so this project really appeals!

Is this something you'd be interested in accepting?

**Comment by geekygirlsarah** [comment]
Oh hey @CandyAngel! I should thank Rachel for passing you along!

I absolutely would love Perl in here! You can tackle it all in one PR or make separate ones for each concept/structure you're adding.

I have docs over at https://docs.codethesaur.us, but they're a bit out of date. (I'm going to try to update them this week/weekend.)  The nutshell is:

- in `web/thesauruses`, add a `perl` directory
- copy over one or more concept .json files from `web/thesauruses/_meta` into the `perl` folder
- In the .json files, fill out the 3 language fields
- You can delete every `name` field (they're not needed in the files, but maybe delete them at the end so you know what the IDs refer to)
- You can add in `"code"` for the code example
- You can add in `"comment"` for elaborating on something that's not clear or multiple ways of doing things
- You can add in `"not-implemented": true` if the thing doesn't exist in Perl.
- Don't delete any of the ID fields.  (leaving them in, even if the language doesn't have it, ensures the system _knows_ the concept doesn't exist in the language)

And reach out if you have questions or want clarifications on anything.

Thank you! 😁

**Comment by CandyAngel** [comment]
I spent some time yesterday and went through this (sorry for the delay, last week was pretty rough) and added all the things that are provided explicitly by Perl (as language features) and some things came up.

What does "Not implemented in this language" mean exactly? Is it "not a language feature", "not possible to do" or "not implemented in the thesaurus"? Should I be adding things that can be done and is there a limit to the scope of this (can only be core, can include core modules, can include third party modules?).

The instructions for running this locally in Docker are "wrong". Mainly, the backticks are not escaped so the command doesn't create a working setup as they get interpreted by the markdown parser and removed (not being familiar with docker, I thought it just took `pwd` as a special word, as opposed to it being a command substitution). In this case, perhaps the entire command should be marked as code? It also says you can attach and Ctrl-C to get to the console of the container but this just shut down the container for me..

Just in case you use what you sent me as a framework for updating the documentation, there was another step (adding the language to the `meta_info.json` file).

I can log another issue for these but thought I might as well mention them here. It would be nice to be able to have a "comment" field in the thesaurus that is rendered on the page (in this case, to mention that Perl is an untyped language for `data_types`). A clearer description of the value storage (hashed list, set) features would be good for figuring out what the equivalent is. For example, Perl's hashes sounds like an amalgamation of, but missing features of both, the hashed list and set. Also, it seems like some things are missing (e.g. inserting/removing things from a set). It would also be nice to be able to provide a list of examples, perhaps rendered as a bunch of collapsed fields (like spoiler boxes)?

I noticed some other things like formatting errors in some of the other thesauruses, so I will fix them up too when I'm done with the Perl side. Is there a preferred indentation style (K&R, OTBS) as I noticed there is inconsistency between some thesauruses.

EDIT: Correct typing errors and added spoilers example.

**Comment by geekygirlsarah** [comment]
I saw this comment passed through my email and I haven't forgotten to answer! Just been a bit busy around the edges of work and all that. I'll try to get to answer all the questions tonight or tomorrow.

I appreciate the thoughtfulness that went into it!

**Comment by geekygirlsarah** [comment]
> What does "Not implemented in this language" mean exactly?

This means that this feature is a thing you can look up on Code Thesaurus, but doesn't necessarily mean the language can do it. So not all languages can do all things other languages can, so this is a way of marking in the file "we're looked at this in the file, and this language can't do it."

> Should I be adding things that can be done and is there a limit to the scope of this (can only be core, can include core modules, can include third party modules?).

Yes! If the core language can do it, please add it. I'm generally leaving it up to the individual implementing it in the data file whether to include it or not as sometimes it's a bit difficult to know whether something should go in or not. I'd rather not include third party libraries, though if there are standard included libraries, you can use those. (So like C++ has a standard template library with a bunch of things, which is fine to include. Boost is a third party library, which would not be fine to include as it'd require a bunch of steps to set up.)

> The instructions for running this locally in Docker are "wrong". Mainly, the backticks are not escaped so the command doesn't create a working setup as they get interpreted by the markdown parser and removed 

You're welcome to file an issue. I can possibly look over it in a bit and try to "fix" it as well. Sorry about the confusion on it!

> Just in case you use what you sent me as a framework for updating the documentation, there was another step (adding the language to the `meta_info.json` file).

I think I just typed that out from memory, so not surprised I forgot a step. I'm glad you included it! I want to rewrite parts of the documentation soon and this is probably helpful to add into it.

> It would be nice to be able to have a "comment" field in the thesaurus that is rendered on the page

There is! Within a language concept, `code: '...'` is required but `comment: '...'` is optional. You can add it in and it will show unformatted below the code for that concept part.

> Also, it seems like some things are missing (e.g. inserting/removing things from a set).

Yes, it's hard to realize every possible way to do every possible thing in every possible language the first time. Definitely file an issue if there's a core concept you think should be added. I'm slowly getting around to trying to add as many things as I can.

> It would also be nice to be able to provide a list of examples, perhaps rendered as a bunch of collapsed fields (like spoiler boxes)?

Some people have done examples by showing comments in between them (like a `// Method 1` and `// Method 2` before them), or by using the comments to kind of describe it. I'd just ask that the code is as close to compileable/runnable/etc. as possible and extra thoughts are in the comment field. I'd like to keep comments in the code block as few as possible to make it easier to compare with other code blocks.

Whew! Did I get them all? Any other thoughts or questions? Feel free to let me know!

**Comment by geekygirlsarah** [comment]
Hey @CandyAngel! I was reviewing the issues and trying to make sure they were all up to date. How is this one coming along? Have you made any progress? Do you have any questions?

**Comment by geekygirlsarah** [comment]
@CandyAngel, last call for this. Did you still want to work on this? I'd be happy to have the contributions! If not, I'll keep the issue but unassign you so others could maybe work on this. (You could always pick it back up later.)

Let me know, and thanks!

**Comment by MaryJoStaebler** [comment]
Need a bit of Perl to start?  I can help get the ball rolling at minimum.

**Comment by geekygirlsarah** [comment]
Sure! Just add any concept to Perl (so any one JSON file) and I'll consider that worth 1 issue (for Hacktoberfest).
