### ISSUE TITLE
Feature: Add unit tests for Django

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#23]
**Description:**
This project has kind of been thrown together over past Hacktoberfests and on Sarah's free time. It's not really had tests added to it because of it's sort of hacky nature. I'd like to have unit test get added in to ensure old features continue to work and new features won't break the site when they go live.

**Requirements:**
* Add some tests for the views
* Add some tests for the models (if they've been added at this point)
* Add some tests for the controllers (if they've been added at this point)

**Claiming This Issue:**
* Please leave a comment below indicating your interest. I can then assign it to you.
* If I don't see an update (comment, code, or PR), then I'll take your name off.
* You would always be welcome to reclaim it again.
* If you can't work on it, either leave a comment or remove yourself from the issue.
* If you have questions, please let me know!

**Comment by Arodriguez340** [comment]
Hi, I would like to contribute. I have basic experience in Django, and also in open source; however, I would like to help as much as I can.

**Comment by geekygirlsarah** [comment]
Hi @Arodriguez340! Yeah, I'd be happy to have the help! Presently I think the develop branch is _still_ PHP but I was working on its Django conversion this week and will probably push the PR today. So maybe in a couple of hours I'll wrap up the last bug and push that in, and you can work on that.

Sound good? Let me know if you have questions.

**Comment by Arodriguez340** [comment]
That sounds great. I'll be waiting for it, If I have any question I'll let you know.

**Comment by geekygirlsarah** [comment]
The Django conversion is now merged into `develop`! Go have fun!

**Comment by geekygirlsarah** [comment]
@Arodriguez340 Were you still wanting to keep working on this? I know you started a PR and it was good so far but you said you had more. Then I ended up closing the PR accidentally due to merging `develop` into `master`... I'd like to PR it again and incorporate your changes so it can add your name as a contributor.

Let me know!

**Comment by geekygirlsarah** [comment]
@Arodriguez340 Hey, I haven't heard back from you in a week (on the PR) and you haven't tried to edit this PR or make a new PR. I'll leave it closed and remove you from this issue. If you want it back, you're welcome to claim it again.
