### ISSUE TITLE
Add Bash script data types

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#235]
# Description

The Bash scripting language is presently not on Code Thesaurus. I would love to see this added and the data types concept added to CT.

# Requirements

* Copy `web/thesauruses/_meta/data_types.json` to a `web/thesauruses/bash/` directory
* Edit the data_types.json file to accurately reflect Bash and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on more specifics of implementing this.

**Comment by ashish-patwal** [comment]
Hey @geekygirlsarah i would love to work on this issue .

**Comment by arpit-omprakash** [comment]
Hey @geekygirlsarah I would like to work on this for hacktoberfest

**Comment by geekygirlsarah** [comment]
Consider it yours! Let me know if you have any questions!

**Comment by geekygirlsarah** [comment]
For Hacktoberfest, make sure your PR is made on or after Oct 1

**Comment by arpit-omprakash** [comment]
Hey @geekygirlsarah, I think the data types might be incomplete.   
Bash offers only a single data type which is a "character string" - basically a string but it is not internally represented as an object or array, but the data_types.json file only offers these two types of string. I think we need to expand the types in the data_types.json file.
For the purpose of this issue, I am submitting a PR with the data type string as array. I will make another issue(if you feel it is necessary) to add other string data types.

**Comment by geekygirlsarah** [comment]
I'll take a look later, but if a data type is missing, then it should be added to the meta language's data_types.json file so it can be properly compared across any language. (So don't try to add a new concept into Bash's file.) If you do edit a meta one, explain the problem in an issue or in the PR directly, and make it a separate PR from doing the Bash one.

(I'm at a conference today so I haven't been able to look at PRs yet)

**Comment by arpit-omprakash** [comment]
No issues. Take your time. I haven't added any new concepts/data types. 
Later, I may add an issue and work on it once I get a bit more familiar with the project.
