### ISSUE TITLE
Add Bash functions

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#236]
# Description

The Bash scripting language is presently not on Code Thesaurus. I would love to see this added and the functions concept added to CT.

# Requirements

* Copy `web/thesauruses/_meta/data_types.json` to a `web/thesauruses/bash/` directory
* Edit the data_types.json file to accurately reflect Bash and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on more specifics of implementing this.

**Comment by cfilipiak31** [comment]
I started working this. Should be submitting PR soon

**Comment by geekygirlsarah** [comment]
Great! I can take a look at the PR a little later today.

Thank you!
