### ISSUE TITLE
Add Bash control structures

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#237]
# Description

The Bash scripting language is presently not on Code Thesaurus. I would love to see this added and the control structures concept added to CT.

# Requirements

* Copy `web/thesauruses/_meta/data_types.json` to a `web/thesauruses/bash/` directory
* Edit the data_types.json file to accurately reflect Bash and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on more specifics of implementing this.

**Comment by arpit-omprakash** [comment]
Hi @geekygirlsarah ! I'd like to work on this one too!

**Comment by geekygirlsarah** [comment]
You can have this one too! Let me know if there's any questions!

**Comment by arpit-omprakash** [comment]
Hey @geekygirlsarah, for this issue also do I need to remove the `"name"` fields?

Update: I tested the site locally, it seems to work without the name fields. So I am removing them for the PR.
