### ISSUE TITLE
404 error pages sometimes have incorrect descriptive text

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#242]
# Expected Behavior

For issues of a concept and language not being implemented in a .json file yet, the page should say that.

# Actual Behavior

It says the language isn't valid.

# Steps to Reproduce the Problem

1. On the home page, choose something that doesn't exist, like Classes, C++, and Scala. (At least, as of Aug 14)
1. The resulting page says "The first language (cpp) isn't valid"

# Additional Info

This will affect `/compare` and `/reference` pages, both of which are in the `web/views.py` file.

**Comment by felis-blue** [comment]
I've had a look at this and I'd like to give it a shot!

**Comment by geekygirlsarah** [comment]
Consider it yours! If you have any questions, let me know!
