### ISSUE TITLE
404 error pages should include details to add language data

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#243]
# Description

When someone looks up a concept in a language, and it doesn't exist yet, it will show a 404 error page that tells that it's missing. I would like the page to show how to contribute that information if the user would like, both the documentation reference and what the file would be in Github.

# Requirements

* The error page should still display an error.
* Below that, it should offer the above ways to contribute
* It should name the location and filename of what it would be (`web/thesauruses/[language]/[concept].json`) and link to the repo, and possibly GitHub's online editor if it lets you do that
* It should also link to the docs (docs.codethesaur.us) on how to contribute

# Additional Notes

Leave a comment to say you're going to work on it and I'll assign you. 

Also leave a comment if you have any questions or want to discuss anything about the ticket.

See docs.codethesaur.us for more details on how to contribute!

**Comment by unnati914** [comment]
could i work on this?

**Comment by geekygirlsarah** [comment]
Yep, I'll assign you! Look at https://docs.codethesaur.us if you want some explanation on the meta info files, or feel free to ask any questions here too!

**Comment by unnati914** [comment]
What i could configure is firstly i have to remove error 404, maybe through meta tags and then add info to add meta data?
Is my approach correct?

**Comment by unnati914** [comment]
okay i need not to remove error

**Comment by RSid** [comment]
I can take a swing at this if you like!

**Comment by geekygirlsarah** [comment]
Sounds good (and looks like you already took that swing)!
