### ISSUE TITLE
Change links on bottom of lookup pages to go to GitHub's editor

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#245]
# Description

Links right now to go the file on GitHub. Those links could go to the editor instead

Ex: 
Before: https://github.com/codethesaurus/codethesaur.us/blob/main/web/thesauruses/csharp/data_types.json
After: https://github.com/codethesaurus/codethesaur.us/edit/main/web/thesauruses/csharp/data_types.json

# Requirements

* Change the file in compare.html and reference.html to reflect this change.

**Comment by himanshu007-creator** [comment]
hi, I would like to work on this issue🙂

**Comment by geekygirlsarah** [comment]
@himanshu007-creator great! I'll assign you. Let me know if you have any questions!
