### ISSUE TITLE
Upgrade README File

### ISSUE THREAD

**Issue by aryasoni98** [codethesaurus/codethesaur.us#249]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1. More Attractive
2. More description

# Additional Info

**Comment by geekygirlsarah** [comment]
@aryasoni98 can you elaborate more on what you mean? Do you have specific suggestions to make it more attractive or descriptive?

**Comment by geekygirlsarah** [comment]
@aryasoni98 I'm going to close this issue since I haven't heard back from you. I'll be happy to reopen it if you have some constructive suggestions we can do to make it better!
