### ISSUE TITLE
Upgrade Bootstrap and Font Awesome libraries

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#262]
# Description

To help improve Lighthouse scores, part of what is needed is to upgrade the libraries for Bootstrap and Font Awesome.

This WILL break things, so it is its own issue now.

# Requirements

1. Upgrade the libraries to the latest version
2. (Optional) Convert them to locally hosted instead of CDN hosted, if needed
3. Upgrade/fix any components that break because of this 

# Additional Notes

If this issue is too big, it can be broken up into multiple issues, either by page or by category (performance, accessibility, etc.)

**Comment by splashley** [comment]
Hey @geekygirlsarah ! I'd like to tackle this issue if that's okay with you. :)

**Comment by geekygirlsarah** [comment]
Yes! I'll put you on it! Feel free to look over any docs at https://docs.codethesaur.us, or you can ask if you need help or have questions. (You can ask here or on Discord.)

**Comment by geekygirlsarah** [comment]
Splitting this into a new ticket. This is now just upgrading libraries, #346 will be for the rest of fixing Lighthouse. @splashley is aware of the update.
