### ISSUE TITLE
Rename thesaurus folders to reflect language version numbers

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#263]
# Description

In `web/thesauruses/`, all the folders just consist of the name of the language. This issue is to allow for things like `python2` and `python3` to exist to allow for comparing language versions too.

# Requirements

1. The easy part: rename the folders to their latest _major_ versions. So `python` to `python3` is fine. `python` to `python391` or `python3.9.1` is not.
2. Update `web/thesauruses/meta_info.json` to reflect the new folder names.
3. The hard part: The syntax highlighting is based on the folder name. This need to be updated to have an additional component to know what language it's in. This could be done in a couple of ways:
    a. Change the language section of `meta_info.json` to be a key (ID) with a value that's an object instead of a string. Add in the language syntax ID in there. This is probably the more "robust" or "correct" solution.
    b. Add the syntax highlighting ID into every _meta language file. This will be simpler to build, but also must have _every_ language file also altered to reflect this (which means changing probably at least 30 language files to also have the same changes).
4. Ensure the Django code reflects whatever change you made.
5. Test it! (It's a larger change that may break some of the built in tests.)

# Additional Notes

This will likely be a big pull request, so it may take longer to review and test. Please be patient! If you're doing this for Hacktoberfest, I'll ensure it gets tagged appropriately and before the end of the month.

**Comment by vickywane** [comment]
@geekygirlsarah I'd like to take this up.

**Comment by geekygirlsarah** [comment]
Yeah @vickywane, I'll assign you!

There's some documentation about how the system works that you can look over, but if you need any help or have any questions, let me know too!

**Comment by geekygirlsarah** [comment]
Hey @vickywane, how is this coming along? I haven't seen any updates and it's been several weeks now. If you still want the issue, let me know otherwise I'll probably unassign you. And if you have any questions, let me know too!

**Comment by cafce25** [comment]
I'd think about adding version subfolders instead like `web/thesauruses/python/3` that way we could still have "default" structure files in `web/thesauruses/python` that apply if the version specific ones don't overwrite it. Another added benefit is that we don't need to change the highlighting logic.

Also if we don't hear back from vickyvane or if they agree I'd take this up.

**Comment by geekygirlsarah** [comment]
I took her off and added you since she hasn't reclaimed in the past 5 days.

I think the folder idea could work. The other thought would be the highlighting logic could change if the meta_info.json file has another field in the languages section for the highlighter. (ex: It's Java, but in the "java18" directory, but highlights with "java".)

Up to you! Both are valid methods.

**Comment by cafce25** [comment]
I have this written up in its own [feature branch](https://github.com/cafce25/codethesaur.us/tree/issue-263-language-folder-versions). But since I based it on the refactor in #459 I'll put off the PR till that is merged in.

**Comment by geekygirlsarah** [comment]
@cafce25 Were you still wanting to work on this? You said you wanted to work on it after #459 and that's merged in now.

**Comment by cafce25** [comment]
No more waiting just busy times it'll need some fixing again. I'll try to visit this during the week.
