### ISSUE TITLE
[Ada] Add Classes

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#264]
# Description

Classes for Ada aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Directions

* On the home page, on the right side (the reference sheet side), choose the language and version, and then the concept.
* The page says the data doesn't exist, but clicking the arrow for the template will provide the template and file for you to use.
* Save that file in `/web/thesauruses/[language]/[version]/[concept].json`.
* Fill out all of the `"code"` sections.
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then delete the `"code"` line.
* Add in `"comment":` if you wish to explain something in the code
* Delete the `"name":` fields before your PR
* Save, commit your code, push to your fork, then make a PR.
* Watch the checks to make sure they all pass. If they don't, click on "Details" and it should tell you what to modify.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by Mansi-Binjola** [comment]
Can you assign this task to me @geekygirlsarah?

**Comment by geekygirlsarah** [comment]
Yeah, I'll assign it to you. You know the drill by now.

**Comment by geekygirlsarah** [comment]
Hey @Mansi-Binjola, how is this coming along? I haven't seen any updates and it's been several weeks now. If you still want the issue, let me know otherwise I'll probably unassign you. And if you have any questions, let me know too!

**Comment by Mansi-Binjola** [comment]
Hey @geekygirlsarah I am really sorry I couldn't give update for a very long time. I got busy with other stuffs. I do want this issue. Can you please give me a week?

**Comment by geekygirlsarah** [comment]
Yep! That's fine. I'll leave you on. I may keep checking back in if I don't hear anything, but there's no pressure to get it done by any particular time.

**Comment by Mansi-Binjola** [comment]
Hey @geekygirlsarah I am really sorry to say that I wouldn't be able to complete this issue. Due to my works and studies, this is getting delayed and I don't others to be stopped from contributing in this issue. Thanks for this opportunity and once again really sorry.

**Comment by cafce25** [comment]
I'm gonna take a stab at this.

**Comment by geekygirlsarah** [comment]
Great, @cafce25 !
