### ISSUE TITLE
Add C++ Classes

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#266]
# Description

Classes for C++ aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Directions

* On the home page, on the right side (the reference sheet side), choose the language and version, and then the concept.
* The page says the data doesn't exist, but clicking the arrow for the template will provide the template and file for you to use.
* Save that file in `/web/thesauruses/[language]/[version]/[concept].json`.
* Fill out all of the `"code"` sections.
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then delete the `"code"` line.
* Add in `"comment":` if you wish to explain something in the code
* Delete the `"name":` fields before your PR
* Save, commit your code, push to your fork, then make a PR.
* Watch the checks to make sure they all pass. If they don't, click on "Details" and it should tell you what to modify.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by somya-15** [comment]
Hello! I (Somya-15) am interested in working on this issue.

**Comment by geekygirlsarah** [comment]
Sure, I'll give you this one too! Same thing: feel free to look at the docs, and let me know if you need any help or have questions!

**Comment by vinayak0127** [comment]
can I work on this issue?

**Comment by geekygirlsarah** [comment]
Somya contacted me outside of Github to get removed, so I can give it to you @vinayak0127 .

Look over the docs, and let me know if you have any questions about it!

**Comment by geekygirlsarah** [comment]
Hey @vinayak0127, how is this coming along? I haven't seen any updates and it's been several weeks now. If you still want the issue, let me know otherwise I'll probably unassign you. And if you have any questions, let me know too!

**Comment by vinayak0127** [comment]
> Hey @vinayak0127, how is this coming along? I haven't seen any updates and it's been several weeks now. If you still want the issue, let me know otherwise I'll probably unassign you. And if you have any questions, let me know too!

Yes, You can unassign, I am a  bit busy with my college work, I won't be able to contribute for a few more weeks.

**Comment by geekygirlsarah** [comment]
That's alright, I remember my college days. If you find yourself with more time and want to tackle it again, let me know!

**Comment by governedbyprudence** [comment]
Hi ! I would like to work on this issue. Can you assign this to me ?

**Comment by geekygirlsarah** [comment]
Hey @governedbyprudence ! I'll pass it to you!

Let me know if you have any questions. We also have docs at docs.codethesaur.us.
