### ISSUE TITLE
Feature: Convert non-existent language items from `null` code to empty object

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#27]
Inside of a language item, code was `null` to symbolize it didn't exist in the language. This could just be an empty object (i.e. `integer_32_bit: {}`). 

Update JSONs and code for this.

**Comment by colindean** [comment]
I _think_ this already works? https://github.com/codethesaurus/codethesaur.us/pull/34/files#diff-0390e01eb8c66734c21151cb8f4dae7dR38 seems to work?

**Comment by vaibhvshrma** [comment]
Hey @geekygirlsarah, 
Wonderful idea behind the project. Could you assign the issue to me? I will make the required changes.
Thanks!

**Comment by geekygirlsarah** [comment]
@vaibhvshrma I have already started working on it but haven't pushed changes yet, mostly because my changes fix 3 issues at the same time (which is why I went ahead and grabbed them myself). I appreciate the enthusiasm though, thanks!
