### ISSUE TITLE
Add Java Classes

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#270]
# Description

Classes for Java aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/classes.json` to the right Java directory in `web/thesauruses/`
* Edit the classes.json file to accurately reflect the latest major version of Java
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by somya-15** [comment]
Hello! I (Somya-15) am interested in working on this issue.

**Comment by geekygirlsarah** [comment]
Yeah! I'll assign you. Look over the docs, and let me know if you have any questions!

**Comment by somya-15** [comment]
I used Visual Studio to create a file named classes.json in the thesauruses>java folder. However, after committing my repository and sending the pull request I am unable to find any lines of code in the file.
I am a first-time open source contributor. Kindly help me resolve this issue.
I have sent an e-mail at coreteam@codethesaur.us with supporting screenshots to aid examination of the probelm.

**Comment by geekygirlsarah** [comment]
I got your email, but looks like you fixed the issue while I was writing the response!

**Comment by somya-15** [comment]
😅Yes, I was also searching for a solution meanwhile.
