### ISSUE TITLE
Add Python Classes

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#273]
# Description

Classes for Python aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/classes.json` to the right Python directory in `web/thesauruses/`
* Edit the classes.json file to accurately reflect the latest major version of Python
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by amitpant14** [comment]
Hi @geekygirlsarah please assign this issue to me.

**Comment by geekygirlsarah** [comment]
Sure, you can have it. Be sure to review the documentation, and let me know if you need help or have any questions!

**Comment by amitpant14** [comment]
Sure, thanks!

**Comment by amitpant14** [comment]
Hey, @geekygirlsarah I had a query. If I understand this right, I will need to edit the copy of classes.json in the python directory. So I will need to edit the 'classes' field in there, updating as required, and no change will be required in the 'categories' field. Is this right?

**Comment by geekygirlsarah** [comment]
Yes, add code, comments, or "not implemented" lines under `classes`. Don't change the categories.

Presently it uses part of the file's categories block for parsing the files, but really doesn't need them, but I haven't taken that code out yet.

**Comment by amitpant14** [comment]
Okay. I have another query. There is a `name` field under each field of `classes`, which doesn't seem to be changing anything. I also checked out classes.json for other languages which have already been contributed to and they don't contain `name`. Should I keep it or remove it?

**Comment by amitpant14** [comment]
Also, how can I write `__init__.py` in the comments? It converts to init with bold. I also tried enclosing it in ` symbol but that converts it into a link.

**Comment by geekygirlsarah** [comment]
Can you paste what you were trying here or send a draft PR so I can see? It doesn't sound like it should turn it into a link, but this might be a use case no one has tried yet and it might be a bug.

**Comment by amitpant14** [comment]
![image](https://user-images.githubusercontent.com/50552215/139455129-67f0ced0-0f36-4b4c-9c9d-6fa9dbe88dd9.png)
This is what it looks like when I enclose `__init__.py` within backticks.

**Comment by geekygirlsarah** [comment]
OH! I finally sat down, easily reproduced this, and am trying to figure out why this is doing what it does.

I'm realizing it's parsing `[anything].py` as a domain name, therefore converting it to a link. Which makes sense. I think I'll probably turn off the auto-linking option. So submit it as-is (so `` `__init__.py` ``) and, for now, it'll show up as a link, but I'll fix it.
