### ISSUE TITLE
Feature: Add New Issue templates

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#28]
I would like a templates so when one creates an issue, you can choose from a bug report or a feature enhancement. This will make it easier and more consistent for me to add new things for others, but also for others to add new issues too.

See: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates on how to do it

Ideas of templates: https://github.com/stevemao/github-issue-templates/

**Claiming This Issue:**
* Please leave a comment below indicating your interest. I can then assign it to you.
* If I don't see an update (comment, code, or PR), then I'll take your name off.
* You would always be welcome to reclaim it again.
* If you can't work on it, either leave a comment or remove yourself from the issue.
* If you have questions, please let me know!

**Comment by mysticknits** [comment]
I can take this one if still needed!

**Comment by geekygirlsarah** [comment]
@laurenamy let me know if you have any questions! My issues haven't had much of a template, but #23 is probably a format I've come closest to. But the ideas link above should be good.

If there's no updates in about a week (so Oct 7), I might take you off the issue.

**Comment by geekygirlsarah** [comment]
@laurenamy It's been about a week so I'm going to take you off so this is open to others to work on. If you want to re-claim it, let me know.

**Comment by sehqlr** [comment]
Hey Sarah, I can work on this one. I'll make simple templates first and then we can refine them through code review?

**Comment by geekygirlsarah** [comment]
That sounds great to me! I'll assign it to you. If I don't see any updates in a week, I'll probably take your name off so others could possibly work on it.

Let me know if you have any questions!

**Comment by geekygirlsarah** [comment]
@sehqlr Hey... how's this coming along?

**Comment by sehqlr** [comment]
I stopped work on this because I ran out of my ADHD meds, but I'm back on them now and I'm going to get this done real soon. Sorry about that :disappointed_relieved:
