### ISSUE TITLE
Add Ada Lists/Arrays/Hashes

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#280]
# Description

Lists/Arrays/Hashes for Ada aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/lists.json` to the right Ada directory in `web/thesauruses/`
* Edit the lists.json file to accurately reflect the latest major version of Ada
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by Mansi-Binjola** [comment]
@geekygirlsarah I think I can solve this issue. Can you assign me this?

**Comment by geekygirlsarah** [comment]
Sure. Same as before, let me know if you have any questions or need help!

**Comment by Mansi-Binjola** [comment]
Hey, @geekygirlsarah while I was researching about this issue, I recently found out about the containers library in Ada ( [See this](https://learn.adacore.com/courses/intro-to-ada/chapters/standard_library_containers.html) ).
Since there is so much to change in my current file, I was thinking of making the file from the beginning. And for that, I will be needing a little more time.

**Comment by geekygirlsarah** [comment]
Oooh, good find! Take your time. I generally check in on people before I unassign them.
