### ISSUE TITLE
Add C# Lists/Arrays/Hashes

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#283]
# Description

Lists/Arrays/Hashes for C# aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/lists.json` to the right C# directory in `web/thesauruses/`
* Edit the lists.json file to accurately reflect the latest major version of C#
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by MaryJoStaebler** [comment]
I can tackle this one, too. 💟

**Comment by geekygirlsarah** [comment]
Great! I'll give it to you too. (Same as before, if you need help let me know!)

**Comment by awray13** [comment]
I'm brand new to all things issues and PRs. But I would love to read through all the documentation and see if could help in any way with this

**Comment by geekygirlsarah** [comment]
Hey @awray13, I think @MaryJoStaebler has this one for now. I have a few other C# issues if you are interested in those! Or you can always clone the project and play around with it to understand it more if you want. I'll definitely be adding more issues in the near future too.

**Comment by awray13** [comment]
@geekygirlsarah okie dokie, that sounds like a great idea. I will clone it and play around with it a bit to better understand it.

**Comment by MaryJoStaebler** [comment]
@geekygirlsarah Would the code of something like swapping elements need to be something out of the box with a language or how to do it with the language?  There's no list.swap(x,y) but more of a few lines of code to do so.   What's a good entry for such a case?

**Comment by geekygirlsarah** [comment]
Generally I say if it's built-in, use it. If you're solving algorithm puzzles, don't. If it's a built-in library (like you have to import it), then include the import and the statement. If it's an outside library, don't do it. 

I'm hopefully working on a "best practices" page soon...
