### ISSUE TITLE
Add Objective-C Lists/Arrays/Hashes

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#288]
# Description

Lists/Arrays/Hashes for Objective-C aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/lists.json` to the right Objective-C directory in `web/thesauruses/`
* Edit the lists.json file to accurately reflect the latest major version of Objective-C
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by vinayak0127** [comment]
Can i work on this issue?

**Comment by geekygirlsarah** [comment]
Yeah @vinayak0127 , I'll let you have it. Review the docs, and let me know if you have questions or need any help!

**Comment by vinayak0127** [comment]
@geekygirlsarah Hey! I have one doubt can I write code snippets in the code from the official documentation or just the keyword
for e.g : 
```
 "name_of_ordered_mutable_list": {
      "name": "What is an ordered, mutable list called?",
      "code": "NSMutableArray *sports = [NSMutableArray arrayWithObjects:@"Cricket", @"Football",@"Hockey", @"Table Tennis", nil];"
},
```
OR

```
 "name_of_ordered_mutable_list": {
      "name": "What is an ordered, mutable list called?",
      "code": "NSMutableArray"
},
```

**Comment by geekygirlsarah** [comment]
I'd like the minimum needed to convey the correct code for the concept. Here `NSMutableArray` might work. While you could use an example (some have), don't make it overly complex or something that certain people would know. It should be something that's as recognizable and simple as possible to go across language barriers (both English as well as the programming language)
