### ISSUE TITLE
Add Python Lists/Arrays/Hashes

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#290]
# Description

Lists/Arrays/Hashes for Python aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/lists.json` to the right Python directory in `web/thesauruses/`
* Edit the lists.json file to accurately reflect the latest major version of Python
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by abxhr** [comment]
I would love to work on this! 🚀

**Comment by geekygirlsarah** [comment]
Sure! Feel free to read over the docs, and let me know if you need any help or have any questions!

**Comment by geekygirlsarah** [comment]
Hey @abxhr, how is this coming along? I haven't seen any updates and it's been several weeks now. If you still want the issue, let me know otherwise I'll probably unassign you. And if you have any questions, let me know too!

**Comment by geekygirlsarah** [comment]
Haven't heard back so I'm removing you. (If you still want it, let me know and I'll add you back.)

**Comment by TomReilly1** [comment]
Hey @geekygirlsarah , I'd love to work on this! Could you assign this to me?

**Comment by geekygirlsarah** [comment]
Yeah! I'll assign you. There are docs at docs.codethesaur.us. Feel free to post any questions you have!

**Comment by TomReilly1** [comment]
Just about done!

I noticed that the instructions say to delete the "names:" fields but looking at other files, they still seem to have it. What should I do in this regard?

**Comment by geekygirlsarah** [comment]
> I noticed that the instructions say to delete the "names:" fields but looking at other files, they still seem to have it. What should I do in this regard?

Good question! So in the early days, a bug in the matching algorithm meant the descriptions on the left side of the site (i.e. "Void function with one parameter") were pulled not from the meta files but from the left/first language file. It wasn't caught for a bit. They should always be taken from the meta files now.

So you can leave them there, but they're extraneous text. Deleting them just simplifies the file, which is why I say remove them. I'll go standardize all the files at some point as some of them have relics still from past versions of CT.

**Comment by TomReilly1** [comment]
Okay going to submit the pull request soon. I removed the "name" fields from the file as well.

If you would like, I could go through all the other non-meta json files in the "/thesauruses" directory and remove all the "names" fields. Could probably makeup a python script to do it.

**Comment by cafce25** [comment]
> If you would like, I could go through all the other non-meta json files in the "/thesauruses" directory and remove all the "names" fields. Could probably makeup a python script to do it.

I have a script if we want that but last time I did remove them @geekygirlsarah  wanted them back (https://github.com/codethesaurus/codethesaur.us/pull/457#issuecomment-996448110) so I wrote another one to put them there again XD.

PS: It's a very undecided issue :laughing:

**Comment by geekygirlsarah** [comment]
> > If you would like, I could go through all the other non-meta json files in the "/thesauruses" directory and remove all the "names" fields. Could probably makeup a python script to do it.
> 
> I have a script if we want that but last time I did remove them @geekygirlsarah wanted them back ([#457 (comment)](https://github.com/codethesaurus/codethesaur.us/pull/457#issuecomment-996448110)) so I wrote another one to put them there again XD.

You lost the context, @cafce25!

So the comment on #457 was for removing them on the template generator (like when someone looks up something and it doesn't exist so it provides the file for you). Without the `name` field, the IDs may not always make sense or may not have all the detail needed for someone to write the file. But upon PRing them, they can be removed. 

So in this case, it's a PR to add a new Python concept file, so they can be removed.

**Comment by cafce25** [comment]
Wait did I totally misunderstand you then and create https://github.com/codethesaurus/codethesaur.us/pull/457/commits/6db1f6a4ff621cf3b0075d5ebbf56f375084b5e4 for nothing O.o

**Comment by geekygirlsarah** [comment]
> Wait did I totally misunderstand you then and create [6db1f6a](https://github.com/codethesaurus/codethesaur.us/commit/6db1f6a4ff621cf3b0075d5ebbf56f375084b5e4) for nothing O.o

Uhhh... maybe? 😬 Though I guess I'm also the one that let it in, so...
