### ISSUE TITLE
Add TypeScript Lists/Arrays/Hashes

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#295]
# Description

Lists/Arrays/Hashes for TypeScript aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/lists.json` to the right TypeScript directory in `web/thesauruses/`
* Edit the lists.json file to accurately reflect the latest major version of TypeScript
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by iaryangoyal** [comment]
Can i DO this? @geekygirlsarah

**Comment by geekygirlsarah** [comment]
Yeah, @iaryangoyal , consider it yours! Look over the documentation, and let me know if you have any questions along the way!

**Comment by abhishek7997** [comment]
Please assign this issue to me. @geekygirlsarah

**Comment by geekygirlsarah** [comment]
@abhishek7997 It's already assigned to someone and I usually give 1-2 weeks for someone to have a chance to do the PR. Sorry!

**Comment by abhishek7997** [comment]
> @abhishek7997 It's already assigned to someone and I usually give 1-2 weeks for someone to have a chance to do the PR. Sorry!

This issue does not have anyone assigned at the moment. That is why I am asking.

The person before be have unassigned themselves.

**Comment by geekygirlsarah** [comment]
Oh... I think Github did a weird caching thing where I thought it was still assigned and didn't see iaryangoyal removed themselves. I'll let you have it then!

Feel free to read over the docs, and ask if you have any questions or need any help!

**Comment by abhishek7997** [comment]
To my knowledge, typescript does not have an "Ordered" list (arrays) by default. So, should I remove the Ordered mutable/immutable lists entirely. Or should I write about the sorting function used to sort arrays in typescript?

**Comment by geekygirlsarah** [comment]
Leave the concepts in there. If there's code, fill that in the `code` line. If the concept doesn't exist, delete the `code` line and replace with `"not-implemented: true"`. You can optionally add a `comment` line.

I think the docs should have examples of this in there.

**Comment by abhishek7997** [comment]
Ok

**Comment by abhishek7997** [comment]
Please check my PR. @geekygirlsarah
