### ISSUE TITLE
Add C# Logic/Math Operators

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#299]
# Description

Logic/Math Operators for C# aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/operators.json` to the right C# directory in `web/thesauruses/`
* Edit the operators.json file to accurately reflect the latest major version of C#
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by VaishnaviNandakumar** [comment]
Hi @geekygirlsarah ! I'd like to contribute to this issue.

**Comment by geekygirlsarah** [comment]
Hey @VaishnaviNandakumar , I'll assign you. Please review the docs and let me know if you need help or have any questions!

**Comment by VaishnaviNandakumar** [comment]
Hi @geekygirlsarah . Can I also include conditional AND, OR operators in operators.json for C#? Only logical operators are provided at the moment.

**Comment by geekygirlsarah** [comment]
That's a good point! Those would have to go in the _meta/operators.json file. That should be its own separate issue/PR. I can do that later today or if you're feeling ambitious, you are welcome to do that!

**Comment by geekygirlsarah** [comment]
@VaishnaviNandakumar I made issue #333 for this. If you want it, comment on there to claim it. Otherwise I'll do it later today.

**Comment by VaishnaviNandakumar** [comment]
@geekygirlsarah I've left a comment
