### ISSUE TITLE
Add JavaScript Logic/Math Operators

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#303]
# Description

Logic/Math Operators for JavaScript aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/operators.json` to the right JavaScript directory in `web/thesauruses/`
* Edit the operators.json file to accurately reflect the latest major version of JavaScript
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by fla-t** [comment]
I will try to complete it today, can u assign it to me?

**Comment by NaimaGhulamMuhammad** [comment]
@geekygirlsarah I would like to work on it.... can you assign it to me

**Comment by geekygirlsarah** [comment]
Yeah, you can have it (though you already did it, lol).

**Comment by geekygirlsarah** [comment]
Uh oh, two of you wanted it and already worked on it. I think @untamedImpala asked first and already made a PR, so I'll give it to you. 

(Sorry @NaimaGhulamMuhammad ! There's some other JS issues as well, and there's working on strings that I'll make an issue for today if you want it)
