### ISSUE TITLE
Add Nim Logic/Math Operators

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#304]
# Description

Logic/Math Operators for Nim aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/operators.json` to the right Nim directory in `web/thesauruses/`
* Edit the operators.json file to accurately reflect the latest major version of Nim
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by geekygirlsarah** [comment]
@juancarlospaco Don't know if you're interested in this or not...

**Comment by juancarlospaco** [comment]
### Division

So in Nim you have 2 kinds of Division, normal division and integer division:

```nim
assert 5  /  2 == 2.5
assert 5 div 2 == 2
```

Python also has this too (`/` and `//`).

But the JSON only has 1.


### Unary minus

Unary minus and unary plus is also missing, the ones to make a number positive or negative,
without sum nor substract 2 numbers. Example `-9` and `+8`.

But the JSON has none.

**Comment by geekygirlsarah** [comment]
Oooh, interesting about the division and good point about the unary operators. I'll edit the meta language file then to mention this.

**Comment by geekygirlsarah** [comment]
Pull request #329 should add the unary and integer division operators! You can add them in Nim now!
