### ISSUE TITLE
Add Python Logic/Math Operators

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#307]
# Description

Logic/Math Operators for Python aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/operators.json` to the right Python directory in `web/thesauruses/`
* Edit the operators.json file to accurately reflect the latest major version of Python
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by RiyaM16** [comment]
Hi @geekygirlsarah!
I'd like to work on this.

**Comment by ujju20** [comment]
Can I work on this issue?

**Comment by geekygirlsarah** [comment]
Hey @RiyaM16 , you commented first so I'll let you have it. Feel free to look over the docs and let me know if you have any questions!

@ujju20 There's a couple of other Python issues still, I think, and I'm about to make one for all the languages in strings, so you can look for that today too if you still want to contribute.
