### ISSUE TITLE
Revise README.md so it reflects correct directions to run Django

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#31]
The `README.md` file shows how to run the newer Django framework, but some have said it's not correct and there's steps missing.

Please modify the `README.md` file so it has easy-to-follow and complete directions for newer people. (For things like "install Python" you can reference other URLs, but if it's specific to this repo, please be descriptive.) It should be accurate enough for beginners to Python as well as experts.

**Comment by colindean** [comment]
Taking this one

**Comment by geekygirlsarah** [comment]
Closed from PR #32
