### ISSUE TITLE
Update meta operators file to add division types and unary operators

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#319]
### Division

So in Nim you have 2 kinds of Division, normal division and integer division:

```nim
assert 5  /  2 == 2.5
assert 5 div 2 == 2
```

Python also has this too (`/` and `//`).

But the JSON only has 1.

### Unary minus

Unary minus and unary plus is also missing, the ones to make a number positive or negative,
without sum nor substract 2 numbers. Example `-9` and `+8`.

But the JSON has none.

_Originally posted by @juancarlospaco in https://github.com/codethesaurus/codethesaur.us/issues/304#issuecomment-934370183_

**Comment by VaishnaviNandakumar** [comment]
Hi @geekygirlsarah! I'd like to contribute to this issue.
