### ISSUE TITLE
Add conditional AND, OR operators in Operators concept file

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#333]
Hi @geekygirlsarah . Can I also include conditional AND, OR operators in operators.json for C#? Only logical operators are provided at the moment.

_Originally posted by @VaishnaviNandakumar in https://github.com/codethesaurus/codethesaur.us/issues/299#issuecomment-935714198_

# Information on the language

In `web/thesauruses/_meta/operators.json`:
1. Add in extra concept IDs in the right category
2. Add the IDs to the bottom part of the file
3. Add appropriate descriptions to the operators
4. Make sure the file is valid JSON syntax
5. Submit the PR!

There's also docs at https://docs.codethesaur.us/thesaurus/ for reference on how the files work.

# Disclaimer
If you would like to work on this issue, please comment here so that you are assigned.

**Comment by VaishnaviNandakumar** [comment]
@geekygirlsarah I'd like to do this!

**Comment by geekygirlsarah** [comment]
So I'm looking at both this issue and the C# issue you grabbed, as well as your code in the PR. I'm thinking some of the changes that should happen might mean a bit more changing around on the meta operators.json file than this issue sort of covers on the surface. So I think I want to go ahead and take this one over so I can make the changes, and it might also affect multiple language operator files that have already been submitted, so I'll need to correct those too. 

I'll make some comments on your PR about what to do for that.
