### ISSUE TITLE
C# Switch statement

### ISSUE THREAD

**Issue by blockingHD** [codethesaurus/codethesaur.us#342]
# Language
C#

# Wrong Field(s)
1. Missing switch statement

# Corrected Information(Optional)
This would be a standard switch:
switch(var) {
    case condition:
        statements;
        break;
    default:
        statements;
        break;
}

However C# has both the switch statement and switch expression which does a similar task. The second use case is more for pattern matching.

**Comment by blockingHD** [comment]
I'd quite like to help contribute to this project as well so happy to take this on.

**Comment by geekygirlsarah** [comment]
Hey @blockingHD, I'll give it to you, but would you mind filling in _all_ of C#'s missing fields? C#'s control structures file was one of the earliest ones, and we've added things to the "meta language" since then and C# is one of the ones that didn't get filled back in after that.

**Comment by blockingHD** [comment]
Sure! I will give it a go over this week.
