### ISSUE TITLE
Update frontend to improve Lighthouse scores

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#346]
# Description

The home page of Code Thesaurus current has the following Lighthouse scores:
- Performance: 93
- Accessibility: 77
- Best Practices: 87
- SEO: 100

The compare and refresh pages currently have approximately** the following Lighthouse scores:
- Performance: 85
- Accessibility: 93
- Best Practices: 87
- SEO: 100

This ticket is to try to update the site to improve the 70s and 80s scores to be at least in the 90s.

** The scores may vary a bit depending on languages compared since keywords are highlighted differently based on the syntax highlighter. As different words are highlighted in different colors, it may increase/decrease some accessibility ratings.

# Requirements

1. Feel free to look at two Lighthouse reports I ran:
    a. https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://codethesaur.us/
    b. https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https%3A%2F%2Fcodethesaur.us%2Fcompare%2F%3Fconcept%3Dfunctions%26lang1%3Dcsharp%26lang2%3Dphp
2. Update the front end, backend, or whatever to try to improve this score.

# Additional Notes

If this issue is too big, it can be broken up into multiple issues, either by page or by category (performance, accessibility, etc.)

**Comment by splashley** [comment]
I'll take care of this Sarah!
