### ISSUE TITLE
Add Visual Basic control structures

### ISSUE THREAD

**Issue by nunogois** [codethesaurus/codethesaur.us#350]
# Description
Control Structures for Visual Basic aren't presently on Code Thesaurus. This issue is to add the language along with that concept to the system.

# Requirements
Create vbnet folder in `web/thesauruses/`
Add vbnet to languages in `web/thesauruses/meta_info.json`
Copy `web/thesauruses/_meta/control_structures.json` to the right vbnet directory in `web/thesauruses/`
Edit the control_structures.json file to accurately reflect the latest major version of Visual Basic
Delete the "name": fields before your PR
Add in "comment": if you wish to explain something in the code
Add in "not-implemented": "true" if the concept doesn't exist in the language. You can then leave "code": blank.

**I would like this issue assigned to me as I have a PR ready to go.**

**Comment by geekygirlsarah** [comment]
Thanks for adding this!
