### ISSUE TITLE
Add Error handling meta concept

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#359]
Add the meta concept for error handling

**Comment by 10raw** [comment]
I would like to work on this issue, can you assign it to me?

**Comment by geekygirlsarah** [comment]
Hey @10raw, I already assigned it to myself and it's about 90% finished. Sorry!

**Comment by geekygirlsarah** [comment]
Closing the issue as it was merged from #397 and wasn't linked when it was merged.
