### ISSUE TITLE
Add TypeScript Strings

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#360]
# Description

Strings for TypeScript aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/strings.json` to the right TypeScript directory in `web/thesauruses/`
* Edit the strings.json file to accurately reflect the latest major version of TypeScript
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by teallarson** [comment]
I'll take this one!

**Comment by geekygirlsarah** [comment]
Consider it yours! Feel free to look over the docs and let me know if you have any questions or need any help!

**Comment by geekygirlsarah** [comment]
Hey @tealjulia, how is this coming along? I haven't seen any updates and it's been several weeks now. If you still want the issue, let me know otherwise I'll probably unassign you. And if you have any questions, let me know too!

**Comment by geekygirlsarah** [comment]
Haven't heard back so I'm removing you. (If you still want it, let me know and I'll add you back.)

Also I'm noticing this is a duplicate of #429 (not sure how that happened 😬) so I'm going to go ahead and close this too.

**Comment by teallarson** [comment]
yep this totally fell out of the back of my brain.  glad to see someone else is on it!
