### ISSUE TITLE
Comment blocks in language files don't allow newlines

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#362]
Newline '\n' is not working in comment.
![image](https://user-images.githubusercontent.com/68701271/136683690-8d3ef491-a270-432c-babb-7ccdaa026c7c.png)

"create_a_unordered_mutable_list": {
      "code": "let arrayName: type[];",
      "comment": "Examples: let scores : (string | number)[];\nlet nums : number[] = [12.34,1,2,3];\nlet arr : Array<any> = [1,2,3,'hi'];\nlet arr : Array<number|boolean> = [1, true, 2];"
    },

_Originally posted by @abhishek7997 in https://github.com/codethesaurus/codethesaur.us/issues/345#issuecomment-939410179_

**Comment by INeedAUniqueUsername** [comment]
I'll claim this issue

**Comment by geekygirlsarah** [comment]
Alright, I'll assign you. You know the drill!

**Comment by geekygirlsarah** [comment]
Haven't heard back so I'm removing you. (If you still want it, let me know and I'll add you back.)

**Comment by aedwardg** [comment]
@geekygirlsarah it looks like this may have been resolved in commit fcfda0f11e901b486b19bfbe11b91450f0891929
Should this issue be closed?

**Comment by geekygirlsarah** [comment]
Huh, weird. This was attached to PR #384 but it never actually closed this issue when that one closed. Weird. But yeah, you're right. It was done!

Thanks for catching that, @aedwardg !
