### ISSUE TITLE
Allow parsing code blocks as array

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#372]
I'm a newbie dev so I might be wrong, but I think the array/ list approach would result in better readability - presently it does not work I tested it.

_Originally posted by @shy-tan in https://github.com/codethesaurus/codethesaur.us/pull/354#discussion_r729988148_

--- 

Note that this is an easier Django change, but will cause a possible need to alter _every_ JSON file if it doesn't allow single lines _and_ code lines.

**Comment by RuggMatt** [comment]
I agree that the array appraoch would be easier to read. 

I can work on this. 

I would imagine supporting both approaches is optimal as the snippets that are only one line long would not have to be put into an array with only one item.

**Comment by geekygirlsarah** [comment]
Yeah, both would be nice, though if it is only reasonable to be just an array, I'm ok with that. I can probably find a way to easily change code lines into code arrays in the files. (Find and replace with regexs is pretty easy for me to pull off.)

This might also break some of the unit tests (notably Language or MetaStructure class tests), so they might need to be updated too.

I'll assign you. Let me know if you have any questions or need any help!
