### ISSUE TITLE
[Concept Request] Basic Input/Output

### ISSUE THREAD

**Issue by INeedAUniqueUsername** [codethesaurus/codethesaur.us#375]
# Description
I'm not sure if this is within the scope of Code Thesaurus (since this deals more with standard library stuff) but it might be helpful to include.

There are many ways to do input/output handling, but some languages such as C++ provide basic text-based input/output in their standard libraries.

The exact details vary a lot (e.g. reading in a number is easier in C++ than in other languages) - so including related things like string/int conversions might be helpful.

Language Examples
- C++: <iostream> and <sstream>
- C#: System.Console
- Java: Scanner, System.out.println

Function Examples
- Read a string
- Read a line
- Read an integer
- Read a float
- Format strings (if not already covered in Strings)
- Convert integer to string (if not already covered in Strings)
- Convert string to integer (if not already covered in Strings)
- Write a string
- Write a line
- Write an integer
- Write a float

# Requirements

# Additional Notes

**Comment by geekygirlsarah** [comment]
Hello! I was working on Exception Handling (was hoping to push it in this weekend but we'll see), and was thinking some of the I/O stuff next!

On my [long-term project board](https://github.com/orgs/codethesaurus/projects/4) for languages/concepts, I was thinking of splitting out file IO, network IO, and console IO. Though many of the things are similar (I think C++'s streams and Java's `System.in`/`System.out`), they might be different. I figured I might take one of those on next.

If you'd be interested, I'd be open to seeing what you (or anyone) might be willing to map out for something like this.

**Comment by blockingHD** [comment]
Looking at this I think you'll find that splitting file, network, and console IO will result in many small entries. Would think that having each under its own section in an IO entry would be better.

Having said that what about references to different in built sql, oracle, etc adapter classes. IE system.data in C# or Java.Sql in Java.

**Comment by geekygirlsarah** [comment]
I suppose it could maybe be small. Though I'm fine with whatever sort of falls logically in place, but also don't want a page to be super huge either because then it's just hard to write.

**Comment by blockingHD** [comment]
Is this being assigned out if so happy to outline the beginning?

**Comment by geekygirlsarah** [comment]
@blockingHD sure, I'll assign this to you! This will probably be a more lengthy PR review, but I'm happy to get outside input!

**Comment by blockingHD** [comment]
Wondering if there should be an area for reading standard data exchange formats such as XML, YAML, and JSON. Possibly including delimited files such as CSV.

**Comment by geekygirlsarah** [comment]
These tend to be popular things, and they're built into enough languages that I'd probably say it makes some sense. Though CSVs get quirky as there's many different ways they can be delimited which sort of gets complicated to write up in this scenario. But you could drop it in and we can think it over!
