### ISSUE TITLE
Add Java Strings

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#379]
# Description

Strings for Java aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/strings.json` to the right Java directory in `web/thesauruses/`
* Edit the strings.json file to accurately reflect the latest major version of Java
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by tarinausher** [comment]
Hi! Can I work on this?

**Comment by geekygirlsarah** [comment]
Sure! I'll give it to you!

Feel free to look over the documentation, and let me know if you have any questions or need any help!

**Comment by geekygirlsarah** [comment]
Hey @tarinausher, how is this coming along? I haven't seen any updates and it's been over 4 weeks now. If you still want the issue, let me know otherwise I'll probably unassign you. And if you have any questions, let me know too!

**Comment by tarinausher** [comment]
Hi @geekygirlsarah, this has been mostly completed, although I had troubles with the last. I tried to add it last week but was having trouble. How do I add the changes made? Thank you!

**Comment by geekygirlsarah** [comment]
Hey Tarina! It looks like you forked the repo, so that's good. I guess first I'd ask if you have used `git` to commit your changes and push those up? If so, then making the pull request is pretty simple and GitHub will walk you through it. If you don't know about Git, then that's a more lengthy set of instructions.

Where are you stuck?

**Comment by tarinausher** [comment]
Okay, I figured out where I was running into issues: I had not set the URL to the forked repo and was still connected to the main one. After setting the correct URL, I was able to push the changes to the forked repo. Is there anything specific I need to do following that?

**Comment by geekygirlsarah** [comment]
Oh no! I've done that before. It's an easy mistake to do! 

Yes, once you've pushed changes to the forked repo, if you go to your repo's main page, you should see something at the top that says you recently pushed to a branch and would you want to make a pull request. Then follow those directions.

If you don't see that box, on your forked repo page, if you click on "Contribute", then the green "Open pull request" button and follow the instructions. (The screenshot shows what to click, though at the moment I don't have changes to make  PR so it's disabled for me. It should be available for you.)
![image](https://user-images.githubusercontent.com/2601974/143775869-ba1eaedd-ceac-49b1-99cd-ea04b99f56bc.png)

**Comment by oneamanish** [comment]
see my pull req.

**Comment by geekygirlsarah** [comment]
@oneamanish, This issue has already been taken by someone and they already made a pull request for it. In addition, your pull request isn't valid and you didn't read the directions so I closed it.

You are welcome to find a new issue, claim it, and follow the directions to contribute code that's beneficial.
