### ISSUE TITLE
Possible typo on About page.

### ISSUE THREAD

**Issue by hgh-bibliophile** [codethesaurus/codethesaur.us#386]
Hello! I really love the idea of this project! I was reading the about page, and I think invited was supposed to be invented? Great project!

https://github.com/codethesaurus/codethesaur.us/blob/1fef910a5837e5b2a936b21b0738f44b6c30d2be/web/templates/about.html#L15

**Comment by geekygirlsarah** [comment]
Thanks! I appreciate this!

And I think you're right, that's definitely a typo. I can fix it (unless you feel strongly inclined to fix it)

**Comment by saracope** [comment]
I'll take this one since there hasn't been any activity on it.

**Comment by geekygirlsarah** [comment]
Thanks @saracope!
