### ISSUE TITLE
Add New Pull Request template

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#39]
I would like a template so when one makes a new pull request, it's more of a form to fill out and can have some consistency and make it easy for myself or future maintainers to review.

See: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates

Ideas of templates: 
- https://github.com/forem/forem/blob/master/.github/PULL_REQUEST_TEMPLATE.md
- https://github.com/stevemao/github-issue-templates

**Comment by Utwo** [comment]
I can help on this one

**Comment by geekygirlsarah** [comment]
Sweet! I'll let you have at it, @Utwo ! If there's no updates in about a week (so Oct 11), I may take your name off of it.
