### ISSUE TITLE
Add support for Clojure

### ISSUE THREAD

**Issue by jeff303** [codethesaurus/codethesaur.us#394]
# Language you would like added
Clojure

# Information on the language
A Lisp dialect that (primarily) runs on the JVM.  The current version is 1.10, so it probably makes the most sense to target that as far as documentation goes.

- [Official website](https://clojure.org/)
- [Style guide](https://clojure.style/)

# Disclaimer
I will create the initial version and fill in what I can.

**Comment by geekygirlsarah** [comment]
Yes! I've had a few people ask about Clojure! 

As for scope of this issue, pick any concept and PR it. You can do them all in series (and get individual PRs for each concept file).
