### ISSUE TITLE
Add C# exception handling

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#403]
# Description

Exception handling for C# aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/exception_handling.json` to the right C# directory in `web/thesauruses/`
* Edit the exception_handling.json file to accurately reflect the latest major version of C#
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then delete the `"code"` line.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by blockingHD** [comment]
Would be happy to take this after #375.

**Comment by geekygirlsarah** [comment]
I'll give this to you too!

**Comment by geekygirlsarah** [comment]
I know you're still working on #375. Do you still want to keep this issue as yours? Figured I'd just double-check!

**Comment by geekygirlsarah** [comment]
Haven't heard back so I'm removing them. (If you still want it, let me know and I'll add you back.)

**Comment by rsk2** [comment]
Hi @geekygirlsarah, I would like to work on this issue.

**Comment by geekygirlsarah** [comment]
@rsk2 alright, it's yours! Let me know if you have any questions. Documentation is at docs.codethesaur.us.

**Comment by rsk2** [comment]
Hi @geekygirlsarah , I have created a PR for this.
