### ISSUE TITLE
Add Python exception handling

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#411]
# Description

Exception handling for Python aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/exception_handling.json` to the right Python directory in `web/thesauruses/`
* Edit the exception_handling.json file to accurately reflect the latest major version of Python
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then delete the `"code"` line.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by abhishak3** [comment]
Please assign this issue to me. I would like to contribute to this.

**Comment by geekygirlsarah** [comment]
Sure, I'll let you have it!

Please read over the documentation, and let me know if you have any questions!

**Comment by abhishak3** [comment]
Hi, @geekygirlsarah .
Sorry, I forgot to create a new branch as mentioned in CONTRIBUTING.md and pushed my commit to the main branch.
Should I close PR #445  and create a new one?

**Comment by geekygirlsarah** [comment]
Hey @abhishak3, that will work. It's your repo, so you can branch or not branch as you see fit. Typically the standard is to make a new branch for those changes so your main branch will always be working code, but in this case you can always compare with CT's main to yours to find those changes and roll back anything that's not working. If you were working on multiple things on the same project, you'd HAVE to make branches for each thing.

For this, this is fine. You can leave it!
