### ISSUE TITLE
Add TypeScript exception handling

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#416]
# Description

Exception handling for TypeScript aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/exception_handling.json` to the right TypeScript directory in `web/thesauruses/`
* Edit the exception_handling.json file to accurately reflect the latest major version of TypeScript
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then delete the `"code"` line.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by PrBart** [comment]
I will take it.

Please, assign it to me.

**Comment by geekygirlsarah** [comment]
Sure @PrBart, I'll give it to you. Please look over the docs and let me know if you have any questions or need any help!

**Comment by PrBart** [comment]
> Sure @PrBart, I'll give it to you. Please look over the docs and let me know if you have any questions or need any help!

Actually i already made a little dive into and wrote most of the cases. Tomorrow morning i will ask several engineers i know to take a look and then will create pull request.

**Comment by geekygirlsarah** [comment]
> Actually i already made a little dive into and wrote most of the cases. Tomorrow morning i will ask several engineers i know to take a look and then will create pull request.

Sounds good! I'm planning to be around tomorrow to try to approve or merge last-minute Hacktoberfest things!
