### ISSUE TITLE
[Ruby] Add strings

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#426]
# Description

Strings for Ruby aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Directions

* On the home page, on the right side (the reference sheet side), choose the language and version, and then the concept.
* The page says the data doesn't exist, but clicking the arrow for the template will provide the template and file for you to use.
* Save that file in `/web/thesauruses/[language]/[version]/[concept].json`.
* Fill out all of the `"code"` sections.
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then delete the `"code"` line.
* Add in `"comment":` if you wish to explain something in the code
* Delete the `"name":` fields before your PR
* Save, commit your code, push to your fork, then make a PR.
* Watch the checks to make sure they all pass. If they don't, click on "Details" and it should tell you what to modify.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by opeco17** [comment]
Hi, @geekygirlsarah
I would like to contribute to Code Thesaurus
Could you please assign this to me?

**Comment by geekygirlsarah** [comment]
I'll give you this one too! Let me know if you have any questions!

**Comment by geekygirlsarah** [comment]
Hey @opeco17, how is this coming along? I haven't seen any updates and it's been over 3 weeks now. If you still want the issue, let me know otherwise I'll probably unassign you. And if you have any questions, let me know too!

**Comment by geekygirlsarah** [comment]
Haven't heard back so I'm removing them. (If you still want it, let me know and I'll add you back.)

**Comment by pulgamecanica** [comment]
Hello, I would like to contribute to solving this issue.
I am an enthusiastic **Ruby** developer and would like to try it very much.
This project is very _awesome_ and I like the website a lot.
I have read the Documentation and especially I read carefully the **"Contributing"** section but if you have any other tips I am interested in having a look before trying it.

> Best regards,
> `André`

**Comment by pulgamecanica** [comment]
I also have a suggestion, in case you haven't considered it.
Perhaps, the JSON should have another section to add the references. I love references, to confirm the information, or if someone wants to dig deeper about a certain subject...
Cheers :)

**Comment by geekygirlsarah** [comment]
Hey @pulgamecanica, I'll assign you then! And yeah, let me know if you have any questions.

And I suppose great minds think alike, there's #188 for the references.

**Comment by pulgamecanica** [comment]
#### Thank's I'll give my best and I will try to be consistent :D

**Comment by pulgamecanica** [comment]
Hello!

Today I will be working on the JSON, yesterday I was able to run the docker-compose without many issues, I worked with Django before and I was happy to see it again, so without further ado, I will do my best and I will use "The Well Grounded Rubyist" 📖  as a reference to get all the ideas straight and without much complications for any reader! :D ✏️

**Comment by pulgamecanica** [comment]
<img width="1902" alt="Screen Shot 2022-10-04 at 13 08 23" src="https://user-images.githubusercontent.com/28810331/193815529-938935de-b8de-4611-9b40-635befa66aef.png">

> `I'm ready to goooo, eager to finish. Again, thanks a lot for letting me contribute, this is so cool!`

**Comment by geekygirlsarah** [comment]
I'm glad you're so excited @pulgamecanica ! I hope you have some fun with it, maybe learn some new things along the way. Again, let me know if you have any questions!

**Comment by pulgamecanica** [comment]
### I have finished, I will perform now a PR :D
I also found one little tiny typo which I would love to fix :D not sure if I should create an issue for it though...
The typo is here:
[https://codethesaur.us/reference/?concept=strings&lang=java%3B17](https://codethesaur.us/reference/?concept=strings&lang=java%3B17)
It's because they forgot to escape the backslash so it actually created a new line instead of showing the new line character.
***
#### IMG showing the exact typo:
<img width="1083" alt="Screen Shot 2022-10-04 at 18 15 14" src="https://user-images.githubusercontent.com/28810331/193884319-5293ef22-0c91-4cad-bc54-6b3c4b93f408.png">

**Comment by geekygirlsarah** [comment]
> I also found one little tiny typo which I would love to fix :D not sure if I should create an issue for it though... The typo is here: https://codethesaur.us/reference/?concept=strings&lang=java%3B17 It's because they forgot to escape the backslash so it actually created a new line instead of showing the new line character.

Good catch! You can sneak it into #555 if you want or you can make a new PR. (no issue needed)

**Comment by pulgamecanica** [comment]
Overall it was very nice to do it, but I couldn't find a proper answer for the second question, so I entered "no need?" because I really didn't know what to put.

<img width="1113" alt="Screen Shot 2022-10-04 at 18 29 22" src="https://user-images.githubusercontent.com/28810331/193886621-fcf8e339-9b4c-483b-83f5-efd8252e2d59.png">

So if you know what I could put there to make it understandable for the readers, I would appreciate it. The string is built.in class which comes along all the Modules for Ruby so it is included by default, I don't know how to explain this very well.

**Comment by pulgamecanica** [comment]
I closed the PR because I didn't want the "No need?" to go there haha I forgot about it... only now I realized

**Comment by geekygirlsarah** [comment]
Oh you don't have to close and open a new one. Just push new changes. Github updates it automatically.

**Comment by pulgamecanica** [comment]
I will sneak that fix for the Java lang on the PR 😄 
Well then, I'll do that.

**Comment by geekygirlsarah** [comment]
Want me to reopen #555 then? You can edit the text of the PR too if something changes.

**Comment by pulgamecanica** [comment]
I would appreciate that, thank you.

**Comment by pulgamecanica** [comment]
Ohhh wow.... that's so nice, it really did it automatically.... now it shows the 4 files changed on the PR.
That's so cool.

**Comment by pulgamecanica** [comment]
Now it says: "Built-in included in the default Modules" instead of "No need? ✅

**Comment by pulgamecanica** [comment]
Srry for not updating this, I'll see how I can finish this soon!

Wrong issue... I meant it for the Ruby operators...
Cheers.

**Comment by geekygirlsarah** [comment]
That's alright! (You can always delete comments too)

**Comment by pulgamecanica** [comment]
I don't like much to delete comments because you might recieve an email about someone saying something and then you can never find it hahaha

**Comment by geekygirlsarah** [comment]
Alright, that's fair too!
