### ISSUE TITLE
[Visual Basic] Add operators

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#434]
# Description

Operators for Visual Basic aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Directions

* On the home page, on the right side (the reference sheet side), choose the language and version, and then the concept.
* The page says the data doesn't exist, but clicking the arrow for the template will provide the template and file for you to use.
* Save that file in `/web/thesauruses/[language]/[version]/[concept].json`.
* Fill out all of the `"code"` sections.
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then delete the `"code"` line.
* Add in `"comment":` if you wish to explain something in the code
* Delete the `"name":` fields before your PR
* Save, commit your code, push to your fork, then make a PR.
* Watch the checks to make sure they all pass. If they don't, click on "Details" and it should tell you what to modify.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by rsk2** [comment]
Hi @geekygirlsarah, I would like to work on this issue.

**Comment by geekygirlsarah** [comment]
Hey @rsk2, I'll assign it to you! Again, let me know if you have any questions. The docs are available too!

**Comment by rsk2** [comment]
Hi @geekygirlsarah, I have created a PR for this issue

**Comment by rsk2** [comment]
Hi @geekygirlsarah, can this count towards hacktoberfest?

**Comment by geekygirlsarah** [comment]
The whole project is opted in for Hacktoberfest, so yes it does. You should see all your PR(s) that count on your Hacktoberfest dashboard. It will take 7 days for them to clear (in case maintainers mark them as spam/invalid) and then it counts.

**Comment by rsk2** [comment]
Ok thanks! I registered later and I couldn't see this so I thought I ask
