### ISSUE TITLE
Feature: Items in a language that aren't supported shouldn't show up as if it was code

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#44]
If a language item that doesn't exist in the language currently shows up as if it was code. This shouldn't show up as monospaced code items but as regular text, or be distinguished somehow differently.

![image](https://user-images.githubusercontent.com/2601974/95128488-7ef47100-0727-11eb-86a0-3e7221c445ee.png)

**Comment by geekygirlsarah** [comment]
@nukefusion You didn't claim to work on this issue, so I can't attach your name to it. Maybe referencing you and your PR will let me do it?

**Comment by nukefusion** [comment]
> @nukefusion You didn't claim to work on this issue, so I can't attach your name to it. Maybe referencing you and your PR will let me do it?

I'm not sure how to claim an issue? Just comment here? PR should be linked already I think.

**Comment by geekygirlsarah** [comment]
Yep. Literally any comment allows me to add your name to it, but apparently not PR-ing against it.

Marking it with your name just says to others that you're doing it and they shouldn't.
