### ISSUE TITLE
Markdowned comments for Python files results in URL links

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#441]
Also, how can I write `__init__.py` in the comments? It converts to init with bold. I also tried enclosing it in ` symbol but that converts it into a link.

_Originally posted by @amitpant14 in https://github.com/codethesaurus/codethesaur.us/issues/273#issuecomment-953555308_

---

The `markdownify` package that comment lines are filtered through can turn anything ending in `.py` into a URL, then apply a link to it. According to [their docs](https://pypi.org/project/markdownify/), this can be turned off by setting the `autolinks` property to `False`.

This issue is to fix that. Set autolinks to false, then test it. Also add a unit test that can validate this as well. (Test that a comment with a markdowned URL turns into a <a> URL, then a general link doesn't get auto-linked.)

**Comment by ryanomor** [comment]
Hi @geekygirlsarah where would the entrypoints be for the the code change and the unit test?

**Comment by geekygirlsarah** [comment]
Without digging too much into it, it's in one of these 4 files that Markdownify is referenced. I'm not sure where you actually make the config change, that'll have to be going into Markdownify's docs to find out.  (Though I can tell you it won't be in requirements.txt)

![image](https://user-images.githubusercontent.com/2601974/139600969-707ef99a-3942-4f92-bdd9-2c61095090df.png)

**Comment by ryanomor** [comment]
Thanks, according to the [docs](https://django-markdownify.readthedocs.io/en/latest/settings.html) it's in the `settings.py`. I primarily work in javascript and java, so not too familiar with the unit test structure in Python. Do I just add a test in the [test_urls.py](https://github.com/codethesaurus/codethesaur.us/blob/main/web/tests/test_urls.py)?

**Comment by geekygirlsarah** [comment]
Good question! So test_urls.py really just tests the various URLs of the site. test_views.py and test_templates.py both test rendering on the site, so one of those might be where those go.

If you haven't done Python, this might be complex, so no pressure to take it. But if you do, it should be one of the simpler bugs we've had on the site.

**Comment by ryanomor** [comment]
I'll give it a shot! Can you please assign it to me?

**Comment by geekygirlsarah** [comment]
Yep! I'll hand it to you. If you have any more questions or need any help, let me know!

**Comment by ryanomor** [comment]
Hi @geekygirlsarah. Please take a look at #443 and let me know what you think!
