### ISSUE TITLE
Bug: Compare/Reference matching function bases off lang1's categories file

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#446]
# Expected Behavior

The meta categories should define how the the language pages (compare/reference) are structured, and the one/two languages are matched up to resemble that. 

For example, for functions, there's:
```
Void Functions
   Function that does not return a value and takes no parameters
   ...
Return Value Functions
   Function that returns a value and takes no parameters
   ...
Lambda/Anonymous Functions
   Anonymous function that takes no parameters
   ...
```
represented by:
```
  "categories": {
    "Void Functions": [
      "void_function_no_parameters",
      ...
    ],
    "Return Value Functions": [
      "return_value_function_no_parameters",
      ...
    ],
    "Lambda/Anonymous Functions": [
      "anonymous_function_no_parameters",
      ...
```
within web/thesauruses/_meta/functions.json

# Actual Behavior

For two languages, it loads categories in the first language, the matches the second to resemble it. The meta language's structure doesn't matter.

For one language, it loads categories on the language. The meta language structure doesn't matter.

Why this is bad: If someone wrote a language file (i.e. Python's functions) and left off categories that don't match the meta language's list, then the second one won't display them, whether they exist or not.

# Steps to Reproduce the Problem

1. Modify any language's set of categories
1. Start the server, then compare or reference that language's concept
1. The site shows based on that language, not keeping it the same as the meta language

# Additional Info

This will be in views.py, starting around line 157 for compare, around 257 for reference.

**Comment by opeco17** [comment]
Hi, @geekygirlsarah 
May I handle this issue?

**Comment by geekygirlsarah** [comment]
Looks like you already did! I'll assign it, and review it tomorrow.
