### ISSUE TITLE
[PowerShell] Add PowerShell Core support

### ISSUE THREAD

**Issue by God-damnit-all** [codethesaurus/codethesaur.us#449]
PowerShell is steadily increasing in popularity ever since going [cross-platform](https://github.com/PowerShell/PowerShell). The object-based pipeline makes it more reliable than ordinary text processing, and they've been adding more functions and operators with every major release. For what it still can't do with its default functionality, it can typically handle by falling back on .NET functions and methods.

Given Bash is already an option on Code Thesaurus, I'd really like to see PowerShell added as an option as well.

**Comment by geekygirlsarah** [comment]
I'd love to see PowerShell/PowerShell Core** too! Are you interested in helping add it? 

** I know there's a .Net vs .Net Core, but have been out of the .Net world long enough to not be sure if there one or both are things anymore.

**Comment by God-damnit-all** [comment]
> I'd love to see PowerShell/PowerShell Core** too! Are you interested in helping add it?
> 
> ** I know there's a .Net vs .Net Core, but have been out of the .Net world long enough to not be sure if there one or both are things anymore.

Would if I could, but family life has been keeping me too busy to contribute much to anything.

**Comment by geekygirlsarah** [comment]
> Would if I could, but family life has been keeping me too busy to contribute much to anything.

That's understandable. I did have someone maybe a month ago talk about adding PowerShell in here, I'll see if I can prompt them again to see if they'd want to do it!
