### ISSUE TITLE
"Back to top" arrow and "Made by" info are arranged weird when viewed on mobile

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#463]
# Expected Behavior

The "Made with ❤️ by..." text would be on the left and the "Back to top" would appear somewhere that makes it not mess up the formatting.

# Actual Behavior

See screenshot below.

# Steps to Reproduce the Problem

1. On mobile, scroll to the bottom of https://codethesaur.us
1. On desktop, shrink the page so it's thin but long.

# Screenshot

![image](https://user-images.githubusercontent.com/2601974/150710222-e471d3af-fcfd-40f8-912f-63cdabe115d6.png)

# Additional Info

Feel free to fix this in a way that looks nice. I don't have a requirement for the way it should look in the end.

**Comment by Mariosyian** [comment]
I have a potential fix ready for a PR. If you are happy with the result could you assign the issue to me?

**Comment by geekygirlsarah** [comment]
I was going to offer it to a junior developer friend, but you clearly already did it. So it's yours!
