### ISSUE TITLE
Contributor count on bottom of pages will max out at 100

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#465]
# Expected Behavior

The contributor count on the bottom of every page should display the _actual_ count of contributors.

# Actual Behavior

The GitHub API limits calls to 100 contributors per "page", and only one page of results is fetched. This number will no longer be correct after we hit 101 contributors.

# Additional Info

In `web/static/js/contributors.js` is where the code to fetch the number. This will need to be rewritten to account for multiple pages of results if over 100 people.

**Comment by splashley** [comment]
Hey Sarah, I'd like to work on this!

**Comment by geekygirlsarah** [comment]
I'll give it to you. I think you know the drill, but ask me off you have any questions!

**Comment by geekygirlsarah** [comment]
@splashley It looks like you claimed this on February 10th. Were you still working on this or should I take your name off so it's open for others? (It's ok either way, just trying to keep the issues list updated!)

**Comment by splashley** [comment]
Working on this now! :)
