### ISSUE TITLE
Missing link to codethesaur.us on Readme

### ISSUE THREAD

**Issue by Rollerss** [codethesaurus/codethesaur.us#47]
Hello geekygirlsarah 

You have a link to codethesaur.us on the [CONTRIBUTING](https://github.com/codethesaurus/codethesaur.us/blob/master/CONTRIBUTING.md) but there is not one on the main Readme.

I think turning the title to a like to website would be a good addition.

**Comment by geekygirlsarah** [comment]
I think I want to close this, though I do so reluctantly.

The link is on the main Github page (see below). Also one should be able to clone the repo and run it locally, which the README talks about. [CONTRIBUTING.md](CONTRIBUTING.md) shows the difference in the two URLs for actually contributing. As a single lone issue, it feels like it's just an easy PR, and sort of against the values of Hacktoberfest. I want to accept it, but I'd really like to encourage more meaningful PRs that help update more documentation outside of just a single link addition to this.

![image](https://user-images.githubusercontent.com/2601974/95534392-3c57c080-09d5-11eb-8bdc-8d26cb2fa7f4.png)
