### ISSUE TITLE
Ordered vs unordered lists are used inconsistently

### ISSUE THREAD

**Issue by cafce25** [codethesaurus/codethesaur.us#481]
# Expected Behavior

Ordered and unordered list concepts are used the same across all languages.

# Actual Behavior

We currently use them in one of 5 ways:
| ordered list | unordered list | languages |
| --------------- | ------------------ | -------------- |
| elements are kept sorted | the element order is preserved | C# |
| not defined | the element order is preserved | Haskell, TypeScript | 
| | | |
| element order is preserved | dictionary | Nim, Swift |
| element order is preserved | set | Ada, obj-c |
| element order is preserved | not defined | go, PHP |

# Requirements
(from @geekygirlsarah) 

This issue is just for editing the meta list. Issue #491 will be for editing the language files themselves.

1. Edit `web/thesauruses/_meta/lists.json` to add in mutable sorted lists and immutable sorted lists
2. Clarify "ordered" vs "sorted" in the descriptions so they're more obvious ordered is just "in an order" and sorted is "are placed in the right order"
3. PR it

**Comment by geekygirlsarah** [comment]
Are you saying the meta concept is defined wrong, ore the language files are inconsistent in how they're implemented?

**Comment by cafce25** [comment]
I'm saying for some languages we interpreted ordered as the element order doesn't change and for others we interpreted it as the datatype keeps the elements sorted.
I see two ways to resolve this:
- Either we introduce some `*sorted_list*` concepts that are for the datatypes that keep the elements sorted, move C# `*ordered_list*` to `*sorted_list*`, move C#, Haskell and Typescript `*unordered_list*` to `*ordered_list*` and maybe fill up their `*unordered_list*` concepts with appropriate datatypes
- or we find better places for Nim and Swifts dictionary-likes as well as for Ada and objective-Cs set-likes, and move their `*ordered-list*` concepts to `*unordered_list*`

In any case we should add documentation for what type of order is meant by the `*ordered*` data structures; element position or element value.

**Comment by geekygirlsarah** [comment]
I've been running around doing in-person activities and traveling and it's been harder to keep up with things, so I think I missed the ordered vs sorted part. It makes more sense now.

I do like "sorted_list" as a name, and I'm guessing it's possible to be mutable and unmutable as well. And yeah, update the descriptions.

Do you want to do this? If not, I can probably take it on this week.

**Comment by geekygirlsarah** [comment]
I also added to the issue text to clarify requirements.
