### ISSUE TITLE
Remove JQuery dependency

### ISSUE THREAD

**Issue by NathanBeddoeWebDev** [codethesaurus/codethesaur.us#482]
# Description

Bootstrap has been upgraded to version 5 which is not dependent on JQuery. We should stop using JQuery in base.html, and update contributors.js to use either fetch, or if we need IE 11 support, then XMLHttpRequest will do.

# Requirements

We need to know whether IE 11 is supported for the project, and if so, that'll decide on what implementation we use for contributors.js.

# Additional Notes
This will bring benefits to FCP and LCP (lighthouse), and reduce the amount of resources needed for users to download.

**Comment by geekygirlsarah** [comment]
Thanks for catching this! This is a good issue to solve for newer people on the project too!

**Comment by barretojs** [comment]
added a PR for this issue.
