### ISSUE TITLE
Add/Correct links on bottom of compare/reference pages no longer work

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#484]
# Expected Behavior

The links at the bottom of reference and compare pages should go to the correct edit page in CT's Github repo.

![image](https://user-images.githubusercontent.com/2601974/165186399-8225341c-725c-4ad1-8f8a-95e0197c22ab.png)

# Actual Behavior

The links go to a 404 page instead.

# Steps to Reproduce the Problem

1. Compare things or look up a reference page (ex: [functions in C# and Python](https://codethesaur.us/compare/?concept=functions&lang1=csharp%3B9&lang2=python%3B3)
1. Click on one of the "Want to add or correct information for..." links
1. Github shows you a 404 page.

# Additional Info

When language versions was added, these links broke. The version number will need to be added into the URL. The templates to edit the URLs in are in `web/templates/` directory but the version number for the language(s) are in `web/views.py`. You'll probably need to pass them to the template somehow.

_Ideally_ we should add tests to ensure those URLs don't break in the future, but i"m not sure how you can actually test that (without maybe pinging GitHub to see if the page returns a 200 vs 404) so this is optional. Please do it if you can figure out how!

**Comment by teallarson** [comment]
I'll do this!

**Comment by geekygirlsarah** [comment]
Consider it yours! Feel free to ask if you have questions.

**Comment by teallarson** [comment]
Yeah... noted in the PR but can't think of a great way to test this that wouldn't also be overkill... Ping Github? Traverse the paths in `thesauruses` and see that they match the generated URLs?  Happy to implement something but haven't thought of what.
