### ISSUE TITLE
[PHP] Fix ordered/unordered/sorted lists

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#504]
# Problem

This issue is to fix the ordered/unordered/sorted lists in PHP's `lists.json` file(s).

When the original meta `lists.json` was released, it was ambiguous whether "ordered" meant "sorted" or not. Due to that ambiguity, different languages implemented it differently.

With the meta language file now fixed and can distinguish distinguish the difference between ordered (items added retain their order), unordered (items added have no guarantee of order), and sorted (items added are rearranged to stay in order), PHP needs to be fixed to correct its usage of this.

The file(s) to update is `/web/thesauruses/php/[version]/lists.json`.

1. The file needs to add the IDs for sorted mutable lists and sorted immutable lists from `/web/thesauruses/meta/lists.json`.
2. Go back over ordered/unordered mutable/immutable lists, and make sure the entries for those 4 sections are all correct, and shift them around if they aren't.

# Additional Info

See @cafce25's comment on #481 [here](https://github.com/codethesaurus/codethesaur.us/issues/481#issuecomment-1109469577) for how this came about and what language edits are needed.

**Comment by LittleBigProgramming** [comment]
I could help with this! Would be a great gateway issue for me. 👍 😄

**Comment by geekygirlsarah** [comment]
Sweet! Consider it yours! Same stuff as before, and let me know if you have any questions!

**Comment by LittleBigProgramming** [comment]
Still working on this!

**Comment by geekygirlsarah** [comment]
Great!
