### ISSUE TITLE
Feature: Add randomized language dropdowns on main home page

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#51]
**Description:**
When you land on the main CT page, the same language shows up for all three drop-downs to choose what languages you want to look up. It just looks odd to me. This issue should help choose a random language to select from the drop-down.

**Requirements:**
- All three language drop-downs on the main page should have random languages specified
- This can be done either by passing in the random languages from `views.py`'s `index` function, or do it directly in the template `index.html`

** Notes:**
Check out https://stackoverflow.com/questions/10860984/random-string-in-template-django where they choose a random thing from a list passed into the template. Use this combined with a `<option selected>` attribute in the drop-downs.

**Claiming This Issue:**
* Please leave a comment below indicating your interest. I can then assign it to you.
* If I don't see an update (comment, code, or PR), then I'll take your name off.
* You would always be welcome to reclaim it again.
* If you can't work on it, either leave a comment or remove yourself from the issue.
* If you have questions, please let me know!

**Comment by hicks2evan** [comment]
Hi @geekygirlsarah, cool project! I opened this PR for this issue https://github.com/codethesaurus/codethesaur.us/pull/62

I was able to build and run locally to test it, thanks for the super clear instructions! I was not able to find any test files in the code, but let me know if I missed anything there and I can update.

Happy Hacktoberfest :)

**Comment by geekygirlsarah** [comment]
There's no tests yet...  😬 There is an issue to start that foundation and someone started working on it but haven't heard back in a bit. I need to check on that...

But thank you! I'll go ahead and assign you since I didn't know you were doing this.

**Comment by hicks2evan** [comment]
Great! Let me know if I should chase down setting up some tests.

**Comment by geekygirlsarah** [comment]
You are more than welcome to. I don't think the other person worked on them anymore. The PR got closed due to the develop branch going away, but you can check out #41 and see what they did, important that stuff in if you want, or start your own!
