### ISSUE TITLE
Add C++ classes 

### ISSUE THREAD

**Issue by governedbyprudence** [codethesaurus/codethesaur.us#518]
# Language

<!C++ -->
Currently c++ classes are not implemented. I would like to implement them. 

# Additional Information
I would add classes and header files information and also oops concepts. 
# Disclaimer
Please assign me this issue. Thank you.

**Comment by geekygirlsarah** [comment]
Reopening until the PR is completed.

**Comment by governedbyprudence** [comment]
Hi ! When writing this issue i was not aware that the issue was already there before. That was the reason i closed this duplicate one :)

**Comment by geekygirlsarah** [comment]
That makes sense. I missed that!
