### ISSUE TITLE
Weird name in _meta/lists.json

### ISSUE THREAD

**Issue by ChaelCodes** [codethesaurus/codethesaur.us#526]
# Expected Behavior

For Unordered Mutable Lists, creating a list should have the same title as creating a list in the other lists: "Create the list".

# Actual Behavior

Unordered Mutable Lists show the title as "unordered" for creating a list.
![unordered is the title](https://user-images.githubusercontent.com/8124558/193468151-93bf264c-2fed-486d-ac77-ea4ed8007ee5.png)

# Steps to Reproduce the Problem

1. Go to a reference sheet for "Lists, Arrays, and Hashed Lists"
1. Look at the "Unordered Mutable Lists" section and the definition for creating a list

# Additional Info

**Comment by geekygirlsarah** [comment]
Fixed with 5b57418a550700b2074ed20b069cbe17919aac36
