### ISSUE TITLE
Meta language List/Array/Hashes file asks you to insert into immutable lists

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#527]
# Language

All/_meta language

# Wrong Field(s)

1. There are fields in Lists/Arrays/Hashes that are for adding items to immutable lists. Those probably shouldn't be there.
2. This probably means while there's "create a [type] list", there should be "create a [type] list from items" kind of thing too.

**Comment by xomiamoore** [comment]
Hi @geekygirlsarah, can I take this one on? :)

**Comment by geekygirlsarah** [comment]
Yeah, I'll give it to you! There's docs at docs.codethesaur.us too. Feel free to ask me any questions you have!

**Comment by xomiamoore** [comment]
Thank you, appreciate how responsive you've been! 🙌🏻

**Comment by cafce25** [comment]
I'm gonna take a look at this.
