### ISSUE TITLE
Feature: Add language versioning to the front-end

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#53]
**Description:**
There will be some differences between different versions of languages. One example is Python 2 vs 3. They are similar but also very different. Someone should be able to choose a language but also a version to compare using the Code Thesaurus system.

**Requirements:**
* On the home page, the languages listed under the two sections should list versions with them next to the languages in sorted order in the dropdowns
* Ensure when submitted, unique values for different versions of the same language are sent to the server
* On the Compare and Reference views, the version number should show up with the language name

**Notes:**
While this front-end issue is separate from the back-end issue (#54), they will have to be merged in together.

**Claiming This Issue:**
* Please leave a comment below indicating your interest. I can then assign it to you.
* If I don't see an update (comment, code, or PR), then I'll take your name off.
* You would always be welcome to reclaim it again.
* If you can't work on it, either leave a comment or remove yourself from the issue.
* If you have questions, please let me know!

**Comment by beingbiplov** [comment]
Hey, 
I was looking at this issue and could not find the version information for languages. The languages and structures are fetched from `meta_info.json` but it does not contain versions of the language. `language_version` is present in `thesauruses/<language_name>/<language_concept.json>` file but it is accessed in `compare` and `reference` view only after the user makes the query. 
Could you please provide more information on this.

**Comment by geekygirlsarah** [comment]
Hey @beingbiplov. Yeah, I kind of figured the front-end and back-end tickets needed to work together, but also figured there was enough to be done separately. So this might take some thought.

Presently aside from a version number in the language concept file, it's not stored anywhere else, but will probably need to be. I think that's what I wanted the back-end ticket for, to figure out the best place for that. 

I think I worded the first point bad and revised it. I wanted the version choices to be done on the home page for the compare/reference sections, not on the compare/reference pages. Sorry about that!

If this is too complex, I can try to take on the backend ticket sooner than later to try to get this ironed out faster.

**Comment by geekygirlsarah** [comment]
Closing as no one implemented this along with #54, but it was essentially solved another way.
