### ISSUE TITLE
[Python] Add queues and stacks

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#536]
# Description

Queues and stacks for Python aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Directions

* On the home page, on the right side (the reference sheet side), choose the language and version, and then the concept.
* The page says the data doesn't exist, but clicking the arrow for the template will provide the template and file for you to use.
* Save that file in `/web/thesauruses/[language]/[version]/queues_stacks.json`.
* Fill out all of the `"code"` sections.
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then delete the `"code"` line.
* Add in `"comment":` if you wish to explain something in the code
* Delete the `"name":` fields before your PR
* If you want to validate your file, run `python manage.py validatelanginfofiles`
* Save, commit your code, push to your fork, then make a PR.
* Watch the checks to make sure they all pass. If they don't, click on "Details" and it should tell you what to modify.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by TrainedPro** [comment]
Hello! I know how to implement stack and queues in Python but how do i do it with a ".json" file with it. I have already read on the website what needs to be done and have seen the samples on the _meta. Do i just need to write instructions for it using the ".json" file?

**Comment by geekygirlsarah** [comment]
Yeah. Basically look at the file and all of the `"code":""` are all empty. You'd fill in the code blocks. or if Python doesn't support it, delete the code line and add `"not-implemented": true` instead. You can add comments too.

You can always look at the site (ex: https://codethesaur.us/reference/?concept=functions&lang=python%3B3 ) and compare it to the file (ex: https://github.com/codethesaurus/codethesaur.us/blob/main/web/thesauruses/python/3/functions.json) to see other examples.

**Comment by geekygirlsarah** [comment]
The other thing is this is for built-in stacks/queues. Don't write algorithms to do it. If there's not a built-in (or importable through standard libraries) way of doing it, then it's "not implemented".

Are you interested in working on this?

**Comment by TrainedPro** [comment]
Yes, i am interested in working on this. Python has a list ".append" and ".pop" function for for both these. My only issue is that i would usually submit a well commented file saying how to do all this but i just do not understand the ".json" format.

I have compared the links you sent me and i think i do understand a bit more now but i hope you will let me know if it is incorrect as this is my first time working on a project like this. If minor mistakes are not an issue, feel free to assign this to me. I will start work on it now.

Thank you!

**Comment by geekygirlsarah** [comment]
JSON is the JavaScript Object Notation. It's basically a bunch of key-value pairs, where values can be numbers, strings, booleans, arrays, or objects. I've tried to abstract the need to know most of it out and mostly just edit code lines. If it's multiple lines, you can either add a `\n` to where it needs to be or just do an array (like `"code": [ "line1", "line2"]`). It's not too bad once you get used to it. Just have to escape strings.

**Comment by geekygirlsarah** [comment]
Want me to assign you?

**Comment by TrainedPro** [comment]
Sure, I can give it a go

**Comment by geekygirlsarah** [comment]
@TrainedPro is still working on this, commenting to leave active.
