### ISSUE TITLE
Feature: Add language versioning to the back-end

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#54]
**Description:**
There will be some differences between different versions of languages. One example is Python 2 vs 3. They are similar but also very different. Someone should be able to choose a language but also a version to compare using the Code Thesaurus system.

**Requirements:**
* When the user requests a specific version of a language, the version should be reflected in the language that gets passed into the template.
* When submitted from the front-end (#53), the view functions should know what language they picked up
* The thesaurus files should be moved to subdirectories reflecting their version numbers
* The Compare and Reference view functions should correctly pick up the correct files from those version

**Notes:**
While the front-end issue (#53) is separate from this back-end issue, they will have to be merged in together.

**Claiming This Issue:**
* Please leave a comment below indicating your interest. I can then assign it to you.
* If I don't see an update (comment, code, or PR), then I'll take your name off.
* You would always be welcome to reclaim it again.
* If you can't work on it, either leave a comment or remove yourself from the issue.
* If you have questions, please let me know!

**Comment by jwalter** [comment]
I have a PR for this

**Comment by geekygirlsarah** [comment]
Thanks for adding the comment. I can now tag you as the assignee.

**Comment by geekygirlsarah** [comment]
Closing #82 and closing #53 means this should be closed as well. (See reasoning why in #82.)
