### ISSUE TITLE
Feature: Add link to contributors to footer

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#55]
**Description:**
At the bottom of each page, it says "Made with ❤ by Sarah Withee." But at this point, this project has been made along with additional contributors. The footer should reflect that!

**Requirements:**
- In the footer part of `base.html`, add a link to the contributors page (see notes)
- Use GitHub's API, find a way to ping the number of contributors and write a small bit of JavaScript code to get the number
- Should say something along the lines of "Made with ❤ by Sarah Withee and `x` contributors." where x is the number of contributors. I'll leave the exact wording up to the issue taker. 

**Notes:**
The link to contributors is here:  https://github.com/codethesaurus/codethesaur.us/graphs/contributors
This looks like possibly the right link to the GitHub API: https://developer.github.com/v3/repos/#list-repository-contributors

**Claiming This Issue:**
* Please leave a comment below indicating your interest. I can then assign it to you.
* If I don't see an update (comment, code, or PR), then I'll take your name off.
* You would always be welcome to reclaim it again.
* If you can't work on it, either leave a comment or remove yourself from the issue.
* If you have questions, please let me know!

**Comment by mysticknits** [comment]
can I give this a shot?

**Comment by geekygirlsarah** [comment]
Yep! @laurenamy, consider it yours!

If I don't see any status updates in a week, I'll remove you (so on the 19th). You could always reclaim it later too.

Let me know if you have any questions!
