### ISSUE TITLE
[C++] Add Input and Output

### ISSUE THREAD

**Issue by adarsh-kishore786** [codethesaurus/codethesaur.us#565]
# Description

Currently, there is no input/output reference sheet implemented for C++ (either version). This issue is to add that concept to the system for C++20.

# Directions

* On the home page, on the right side (the reference sheet side), choose the language and version, and then the concept.
* The page says the data doesn't exist, but clicking the arrow for the template will provide the template and file for you to use.
* Save that file in `/web/thesauruses/cpp/[version]/io.json`.
* Fill out all of the `"code"` sections.
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then delete the `"code"` line.
* Add in `"comment":` if you wish to explain something in the code
* Delete the `"name":` fields before your PR
* Save, commit your code, push to your fork, then make a PR.
* Watch the checks to make sure they all pass. If they don't, click on "Details" and it should tell you what to modify.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by geekygirlsarah** [comment]
Updated title/description to add more info. Thanks for filing this @adarsh-kishore786 !

**Comment by adarsh-kishore786** [comment]
I hope this sounds fine? If not please tell me

**Comment by adarsh-kishore786** [comment]
Also, for some sections like Networks, JSON etc, there are no inbuilt libraries available as such. However, there are many 3rd party libraries to do the job. In cases like these, should I mention the API provided by anyone of the third-party libraries,?

**Comment by geekygirlsarah** [comment]
> Also, for some sections like Networks, JSON etc, there are no inbuilt libraries available as such. However, there are many 3rd party libraries to do the job. In cases like these, should I mention the API provided by anyone of the third-party libraries,?

No. _Only_ use built-in functions or standard libraries already in the language. So for C++, just the `std` libraries. (So no Boost or other things.)  

Also if you have to write an algorithm to make it work, the language doesn't have it. So just mark it as "not-implemented".

**Comment by geekygirlsarah** [comment]
(I assume you're wanting to work on this. If not, you or I can unassign you.)

**Comment by adarsh-kishore786** [comment]
I am working on this @geekygirlsarah. Thanks for the inputs!

**Comment by adarsh-kishore786** [comment]
Also, can I assume that we have used `using namespace std;` in the program? Or should I namespace the functions properly?

**Comment by geekygirlsarah** [comment]
Since that's not a default assumption for the language, let's say no. You could maybe say somewhere towards the beginning in a comment that all functions are in the `std` namespace and therefore you're writing it like that, but I'd probably rather have it the "proper" way and just prefix the functions/classes with `std::` first.

**Comment by adarsh-kishore786** [comment]
Understood. Thanks!

**Comment by adarsh-kishore786** [comment]
I have added the required webpage with what I know and found. If there's anything missing or which can be changed, please let me know!

**Comment by geekygirlsarah** [comment]
> I have added the required webpage with what I know and found.

Yep, I get notifications when people make comments or PRs on the project.

> If there's anything missing or which can be changed, please let me know!

I would have on the PR itself. But it looked good and passed tests, so I merged it in!
