### ISSUE TITLE
C# is missing some data types

### ISSUE THREAD

**Issue by Rollerss** [codethesaurus/codethesaur.us#575]
# Language

C# is missing some data types.

# Wrong Field(s)
1. Signed 8-bit integer -> Unknown
1. Unsigned 8-bit integer -> Unknown
1. Unsigned 16-bit integer -> Unknown
1. Unsigned 32-bit integer -> Unknown
1. Unsigned 64-bit integer -> Unknown
1. Character -> Unknown
1. String as an object -> Unknown  

# Corrected Information(Optional)
1. Signed 8-bit integer -> sbyte
1. Unsigned 8-bit integer -> byte
1. Unsigned 16-bit integer -> ushort
1. Unsigned 32-bit integer -> uint
1. Unsigned 64-bit integer -> ulong
1. Character -> char
1. String as an object -> string

# Additional Information
[Built-in types (C# reference)](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/built-in-types)
# Disclaimer
If you would like to work on this issue, please comment here so that you are assigned.

**Comment by Rollerss** [comment]
Please assign this issue to me

**Comment by geekygirlsarah** [comment]
I'll give it to you, @Rollerss . Also thanks for catching this and filing it!
