### ISSUE TITLE
Add R language

### ISSUE THREAD

**Issue by monkeywithacupcake** [codethesaurus/codethesaur.us#577]
# Language you would like added
R  
[R project](https://www.r-project.org/about.html)

# Information on the language
This is a language primarily for stats that has grown into a popular tool for data science that is being used to create webpages and books, so it is more flexible than originally imagined.

# Disclaimer
If you would like to work on this issue, please comment here so that you are assigned.
I'd like to work on this issue

**Comment by geekygirlsarah** [comment]
Ah yes, I had to fight with R at my last job and having it in here would have been helpful. Thanks for adding this!

**Comment by monkeywithacupcake** [comment]
I tried to get started on this one - but not assigned, so no PR. 

Also , I added the language in `meta_info.json` and was able to get a template - so I know that it sees "r". And then I added a new folder "r" with one concept area `classes.json`. When I test in my container, I cannot see R now as a choice under classes (or anything, but that's the only one I built a json for). 

Here's an image that shows folders on left with new file and included in `meta_info.json` on right.
<img width="561" alt="Screen Shot 2022-10-16 at 14 02 06" src="https://user-images.githubusercontent.com/7316730/196058139-d0b0124a-821c-42d9-b118-cbe5966f6eaf.png">

I must have missed this in the guide. Or, I should've waited longer before attempting this because there is some behind the scenes stuff not in the docs that needs to happen besides what it says for a new language.

**Comment by monkeywithacupcake** [comment]
Edit, never mind. I did it wrong. Future users - you have to make a folder for the major version number. I read about this and STILL missed it as a step. all better now.

**Comment by geekygirlsarah** [comment]
> Future users - you have to make a folder for the major version number. I read about this and STILL missed it as a step. all better now.

Is this a case of the documentation is wrong somewhere, or is this a case of the step is there and you just missed it?

**Comment by geekygirlsarah** [comment]
Also assigned you as it sounds like you wanted it!

**Comment by monkeywithacupcake** [comment]
> > Future users - you have to make a folder for the major version number. I read about this and STILL missed it as a step. all better now.
> 
> Is this a case of the documentation is wrong somewhere, or is this a case of the step is there and you just missed it?

This is a case of the documentation doesn't tell you that you need to make a version folder 
See [Docs issue #32](https://github.com/codethesaurus/docs/issues/32)
