### ISSUE TITLE
Bug: Correct README to show correct directions for Win, and how to set up virtual environment

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#58]
**Description:**
The directions to run the project on the [README.md](README.md) file show a really simplistic set of steps for working with Python to run the app. These can be incorrect due to operating systems, multiple Python installs (2.x and 3.x), or some other factors. Some want to use virtual environments instead.

This issue should make more specific directions for operating systems as well as include virtual environments.

**Requirements:**
* Should have valid directions to run the app using Python 3 (probably with the `python3` command instead)
* Should offer a way to do virtual environments (`pyenv` or `venv` perhaps)
* Should include directions a bit more specific to Windows.
* Does _not_ need to tell how to install Python, but should link to places to install it (or just show something like `brew install python` or `apt-get install python3` or `choco install  python3` or other variations)
* _Does_ need to assume a user is not familiar with the install process of this app and try to make it as clear and friendly as possible

**Claiming This Issue:**
* Please leave a comment below indicating your interest. I can then assign it to you.
* If I don't see an update (comment, code, or PR), then I'll take your name off.
* You would always be welcome to reclaim it again.
* If you can't work on it, either leave a comment or remove yourself from the issue.
* If you have questions, please let me know!

**Comment by mamadou-diallo** [comment]
I can include some directions on how to run this on Windows. If thats okay with you?

**Comment by bhantsi** [comment]
Assign this to me, I can do it

**Comment by geekygirlsarah** [comment]
I split out Windows, Mac, and Linux edits to the `README`. Do you still want it? I'll assign it if so.

**Comment by bhantsi** [comment]
Yes, please

**Comment by geekygirlsarah** [comment]
Alright! I'll give it to you. If I don't see any sort of update in a week, I'll take you off. (You can always reclaim it too.)

And please leave any comments with questions that you have!
