### ISSUE TITLE
[Lua] Add functions

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#582]
# Description

Functions for Lua aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Directions

* On the home page, on the right side (the reference sheet side), choose the language and version, and then the concept.
* The page says the data doesn't exist, but clicking the arrow for the template will provide the template and file for you to use.
* Save that file in `/web/thesauruses/[language]/[version]/functions.json`.
* Fill out all of the `"code"` sections.
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then delete the `"code"` line.
* Add in `"comment":` if you wish to explain something in the code
* Delete the `"name":` fields before your PR
* Save, commit your code, push to your fork, then make a PR.
* Watch the checks to make sure they all pass. If they don't, click on "Details" and it should tell you what to modify.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by srigundeti10** [comment]
@geekygirlsarah   please assign me

**Comment by geekygirlsarah** [comment]
I'll give it to you @srigundeti10 ! Read over the docs and let me know if you have any questions!

**Comment by srigundeti10** [comment]
@geekygirlsarah so sorry but i am unable to do it 
sorry

**Comment by srigundeti10** [comment]
Hope someone more deserving gets it :)
All the best everyone :)

**Comment by geekygirlsarah** [comment]
That's ok @srigundeti10, sometimes it happens. Thanks for trying!

**Comment by srigundeti10** [comment]
> That's ok @srigundeti10, sometimes it happens. Thanks for trying!

😊😊thankyou so much you are so caring

**Comment by geekygirlsarah** [comment]
> 😊😊thankyou so much you are so caring

Thanks! I try. Also found people are donating their time for free, and it's for a side project I don't make money off of (in fact I pay for hosting), so I'm just happy people like the tool and are willing to help make it better. I don't have time to add all the languages to it!

**Comment by srigundeti10** [comment]
All the best 😊

**Comment by ayaan-qadri** [comment]
Hey, I'm working on this !!

**Comment by geekygirlsarah** [comment]
I'll assign you @PentW0lf
