### ISSUE TITLE
[Lua] Add queues and stacks

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#586]
# Description

Queues and stacks for Lua aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Directions

* On the home page, on the right side (the reference sheet side), choose the language and version, and then the concept.
* The page says the data doesn't exist, but clicking the arrow for the template will provide the template and file for you to use.
* Save that file in `/web/thesauruses/[language]/[version]/queues_stacks.json`.
* Fill out all of the `"code"` sections.
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then delete the `"code"` line.
* Add in `"comment":` if you wish to explain something in the code
* Delete the `"name":` fields before your PR
* Save, commit your code, push to your fork, then make a PR.
* Watch the checks to make sure they all pass. If they don't, click on "Details" and it should tell you what to modify.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by kunalsingh1301** [comment]
@geekygirlsarah can you assign me?

**Comment by Subhajit767** [comment]
please assign this to me

**Comment by geekygirlsarah** [comment]
@kunalsingh1301 was first but also grabbed another issue. Do you still want it?

**Comment by ayaan-qadri** [comment]
I'll work on it and if you want to give me any additional information about this, Please lemme know.

**Comment by ayaan-qadri** [comment]
Hey sarah, there is no built-in queue data type in Lua so can i take this: https://codethesaur.us/reference/?concept=queues_stacks&lang=javascript%3BECMAScript+2023 as reference or should i just let it "not-implemented" ?

**Comment by geekygirlsarah** [comment]
Yeah that works. Obviously modifying it for Lua and not JS.
