### ISSUE TITLE
[Python] Missing info on Python strings

### ISSUE THREAD

**Issue by pythoninthegrass** [codethesaurus/codethesaur.us#590]
# Language

[Comparing Python's and Go's Strings](https://codethesaur.us/compare/?concept=strings&lang1=python%3B3&lang2=go%3B1)

# Wrong Field(s)
(for Python)
1. Default byte encoding (ex: ASCII UTF-8, UTF-16, etc.) 
2. Create new multi-line string
3. Assign string from another string
4. Destroy string and/or clear/empty string

# Corrected Information(Optional)
1. [UTF-8](https://realpython.com/python-encodings-guide/#python-3-all-in-on-unicode)
2. [Multi-line Docstrings](https://peps.python.org/pep-0257/#multi-line-docstrings)
    ```python
    example = """New
    Multi-line
    String
    """
    ```
3. Assign string from another string
    ```python
    >>> example = "New String Example"
    >>> another = example
    >>> print(another)
    New String Example
    ```
4. It's possible to negate a string or straight up delete an [object](https://www.tutorialspoint.com/How-to-destroy-an-object-in-Python), although I haven't personally had to do the latter. Depends on how you define _destroy_. 
    ```python
    >>> example = ""
    >>> print(example)

    >>> print(another)
    New String Example
    >>> if not example: print('true')
    ...
    true
    >>> example = "Newish string example"
    >>> if not example: print('true')
    ...
    >>>
    ```

# Additional Information

# Disclaimer
I can fix these specific fields. Don't have the bandwidth for a comprehensive review of Python v. Go, but cursory glance was enough to see some obvious errors.

Since one of my PRs for [Hacktoberfest](https://hacktoberfest.com/) wasn't accepted by the competition organizers, I'd appreciate a `hacktoberfest-accepted` label if that's not too much trouble 👌

**Comment by geekygirlsarah** [comment]
Yeah, it does look like some of the Python fields aren't up to date. You're welcome to do it! I can assign you. (I'll rename the issue so it more accurately reflects what's wrong here.)

The whole repo is opted in for Hacktoberfest so every PR merged should count. I haven't labeled any PR with that label yet but if you have issues let me know and I can add the extra label. (I say that as it's more likely I'll forget in all the notifications/issues/PRs I'm getting.)

**Comment by pythoninthegrass** [comment]
> The whole repo is opted in for Hacktoberfest so every PR merged should count.

Not your first rodeo, eh? 😎 

Appreciate the swift response! I'll open a PR this week.

**Comment by pythoninthegrass** [comment]
Done! #600

**Comment by geekygirlsarah** [comment]
> Not your first rodeo, eh? 😎

Nope. I think it's the 4th (?) Hacktoberfest CT has been in? The first year was just me. 2nd had about 15 PRs, 3rd about 71 PRs, and this year is 35 PRs so far. And I haven't heard of anyone not getting credit for contributions here yet, but I'd also reach out to the mods of Hacktoberfest too if someone got turned down. (I've had to talk to them before last year, they're fairly good people.)

**Comment by pythoninthegrass** [comment]
Color me impressed! I trust your informed judgment haha
________________________________

**Comment by geekygirlsarah** [comment]
Just let me know if you don't see it in the dashboard, @pythoninthegrass !
