### ISSUE TITLE
Clear Console Output not Cutput in meta and templates

### ISSUE THREAD

**Issue by monkeywithacupcake** [codethesaurus/codethesaur.us#591]
# Expected Behavior

`io.json` should have the concept "clear_console_output"  

# Actual Behavior

`io.json` has "clear_console_cutput"

# Steps to Reproduce the Problem

1. Open io.json
1. OR copy templated code for new reference from io  for example`http://localhost:8000/reference/?concept=io&lang=r%3B4`

# Additional Info

Correcting this typo could result in breaking changes because all of the io.jsons would be wrong. Note that it is not filled in for many languages, so this may be a not big issue. 

<img width="479" alt="Screen Shot 2022-10-16 at 14 47 08" src="https://user-images.githubusercontent.com/7316730/196059809-aeada2c6-321b-4f2c-b4b9-4645c28f48e4.png">

**Comment by geekygirlsarah** [comment]
Dang, you're finding all the problems! Good catch!

My "replace across all files" search in PyCharm found this in 2 files, so it's probably not a hard fix in reality. Do you want this issue? Otherwise I can probably fix it tonight.

**Comment by monkeywithacupcake** [comment]
I'll do it. I feel committed to killing this typo.
