### ISSUE TITLE
Operands and certain operators missing for C#

### ISSUE THREAD

**Issue by rsk2** [codethesaurus/codethesaur.us#603]
# Expected Behavior

When comparing C# operators with any other language, the code should contain operands

It should contain the available C# logical operators 

It should contain the available C# bit-wise operators

# Actual Behavior

The operands, logical operators and bitwise operators are missing

# Steps to Reproduce the Problem

1. Go to code thesaurus main page.
2. In the learn a language table, select "Logical and Mathematical/Arithmetic operators". 
3. Pick C# as one of the language and choose any other language.
4. Click on Go

**Comment by geekygirlsarah** [comment]
Ah yeah, I think those operators were added as an operators version 2, but the language was added before the changes were so it left this hole. Thanks for catching!

**Comment by gutogalego** [comment]
Found the issue, I'll fix it today.

**Comment by geekygirlsarah** [comment]
Great! I'll assign to you.

**Comment by geekygirlsarah** [comment]
This was fixed in #603 but didn't close because it was linked wrong. This issue is done.
