### ISSUE TITLE
[Javascript] Add missing concepts for ECMAScript 2009 and 2023

### ISSUE THREAD

**Issue by ulyssear** [codethesaurus/codethesaur.us#609]
# Language

Javascript (or to be more precise, ECMAScript 2009 and ECMAScript 2023)

# Missing concepts

These concepts have to be added via PRs :

- [x]  Control Structures
   - #613  
- [x] Data Types
   - #608
- [x] Exception Handling
   - #614 
- [x] Functions, Methods, and Subroutines
   - #630 
- [x] Logical and Mathematical/Arithmetic Operators
   - #631 
- [x] Queues and Stacks (neither ECMAScript 2020 nor 2021 don't have this concept)
   - Issue: #541 
   - #647
   - **OBSOLETE**:  PR #563 which adds the concept for ECMAScript 2020 and 2021
- [x] Strings
   - #634 

# Additional Information

To avoid creating X issues about adding concepts for javascript, I decided to create an issue to track the completion of meta files.

~~Since the "queues and stacks" concept is not present in any version, a new issue may be created for this concept.~~

# Disclaimer

I'm already working on some concepts but some help is welcome indeed!

**Comment by geekygirlsarah** [comment]
The "epic" issue for this works for me!
