### ISSUE TITLE
Bug: Correct README to show correct directions for Linux, and how to set up virtual environment

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#61]
**Description:**
The directions to run the project on the [README.md](README.md) file show a really simplistic set of steps for working with Python to run the app. These can be incorrect due to operating systems, multiple Python installs (2.x and 3.x), or some other factors. Some want to use virtual environments instead.

This issue should make more specific directions for operating systems as well as include virtual environments.

**Requirements:**
* Should have valid directions to run the app using Python 3 (probably with the `python3` command instead)
* Should offer a way to do virtual environments (`pyenv` or `venv` perhaps)
* Should include directions a bit more specific to Linux.
* Does _not_ need to tell how to install Python, but should link to places to install it (or just show something like `brew install python` or `apt-get install python3` or `choco install  python3` or other variations)
* _Does_ need to assume a user is not familiar with the install process of this app and try to make it as clear and friendly as possible

**Claiming This Issue:**
* Please leave a comment below indicating your interest. I can then assign it to you.
* If I don't see an update (comment, code, or PR), then I'll take your name off.
* You would always be welcome to reclaim it again.
* If you can't work on it, either leave a comment or remove yourself from the issue.
* If you have questions, please let me know!

**Comment by jlolzzz** [comment]
I can help out with this, if it is still needed.

**Comment by geekygirlsarah** [comment]
Oh cool! Yeah I can pass it over to you. I'll give about a week and if I don't see updates, I'll unassign it so others can work on it. (If this happens, you can always reclaim something.)

If you have any questions, let me know!

**Comment by jlolzzz** [comment]
Awesome, thank you.
