### ISSUE TITLE
Java missing absolute value

### ISSUE THREAD

**Issue by jeff303** [codethesaurus/codethesaur.us#617]
# Language

Java (all versions)

# Wrong Field(s)
1. _Absolute value operator_  under _Operators_

The language itself doesn't provide a built-in operator, but it's part of the core JDK, which is close enough.

**Comment by geekygirlsarah** [comment]
Yeah, if there's a function to do it, that counts too!

**Comment by geekygirlsarah** [comment]
I'm reading #619 and #620 and this are all essentially the same issue as they're the same language in the same file and probably could have had one PR to fix them all.
