### ISSUE TITLE
[Java] Missing bitwise and logical operators

### ISSUE THREAD

**Issue by jeff303** [codethesaurus/codethesaur.us#619]
# Language

Java (all versions)

# Wrong Field(s)
1. _Bitwise AND operator_
1. _Bitwise OR operator_
1. _Bitwise NOT operator_
1. _Bitwise XOR operator_
1. _Logical AND operator_
1. _Logical OR operator_
1. _Logical NOT operator_

These are all supported in Java, with almost the same syntax as in C-style languages.

**Comment by geekygirlsarah** [comment]
Adding in data from #620 as they're similar issues that affect the same language and files.

**Comment by akkshayTandon** [comment]
Assign it to me , I will update it.

**Comment by geekygirlsarah** [comment]
Closed as this was done in #621
