### ISSUE TITLE
Java missing logical operators

### ISSUE THREAD

**Issue by jeff303** [codethesaurus/codethesaur.us#620]
# Language

Java (all versions)

# Wrong Field(s)
1. _Logical AND operator_
1. _Logical OR operator_
1. _Logical NOT operator_

These are all supported in Java with syntax almost identical to C-style languages.

**Comment by geekygirlsarah** [comment]
I'm going to combine this issue with #619 because they're all in the same file and update the same language. So I'm going to close this ticket in favor of the larger #619.
