### ISSUE TITLE
Clojure language version is not listed correctly in directory structure

### ISSUE THREAD

**Issue by jeff303** [codethesaurus/codethesaur.us#622]
# Language

Clojure

# Additional Information

Because of the directory structure (wherein the Clojure directory has only a subdirectory named `1`), the version that appears in the UI is not correct ("Clojure 1"), even though the `language_version` listed within the inner JSON files is correct.

Should probably give this a wildcard type name that is more correct (such as `1.x`).  Will have to check whether any of the particulars listed so far have changed across the versions (but I don't think they have).

**Comment by geekygirlsarah** [comment]
This sounds similar to the versioning on Rust, which only has one major version (v1) but multiple minor versions (v1.x), and each additional version is adding features or updating old ones. I think for consistency, as well as ease of maintainability (it's hard enough to even just get one minor language in here, the maintainability of _every_ one would just be too much for a side project), I'm going to follow the same rule established when we added versioning, which is we keep all major versions (Clojure 1, Clojure 2 if it comes out) and only the latest minor version (whatever Clojure 1.x is). If something updates and isn't in an old version, add a comment like "Added in version 1.23" or something. But all languages in CT presently work this way.

(Full conversation of the determination behind this logic starts at https://github.com/codethesaurus/codethesaur.us/pull/467#issuecomment-1038262755 )

I'm going to go ahead and close this as it presently still fits the "best practices" we've built. If you have thoughts on why we should update this line of thinking, feel free to let me know!
