### ISSUE TITLE
Update generate_template function and add UI for incomplete file

### ISSUE THREAD

**Issue by ulyssear** [codethesaurus/codethesaur.us#635]
# Description

~~Add a `draft` key in the meta of a thesaurus to add a draft version of the thesaurus.~~

A new command `generate_missing_template` executes the command `generate_template` for each missing thesaurus.

~~Also, add the argument `draft` for the command `generate_template` and function `generate_language_template`.~~

And finally, an alert on "compare" and "reference" warns about the draft version of the thesaurus with a link to GitHub.

~~PS: To summarize the use of "draft" mode, this can be used to identify the incomplete thesaurus.~~

# Requirements

A PR will be available with these features.

# Additional Notes

![image](https://user-images.githubusercontent.com/11415595/198896345-65f3d56c-3fa0-49bb-98e2-2a3a611e5b8f.png)

**Comment by cafce25** [comment]
Honestly, I'm failing to see what usecase a dedicated draft mode has in the current mode of only being able to create new concepts via PR, as long as they are not merged, they're a 'draft' after that, I think we trust the data is correct (as far as we can tell) and should display it as such. A note & call to contribute in case some structure file is incomplete would be nice though.

**Comment by ulyssear** [comment]
> Honestly, I'm failing to see what usecase a dedicated draft mode has in the current mode of only being able to create new concepts via PR, as long as they are not merged, they're a 'draft' after that, I think we trust the data is correct (as far as we can tell) and should display it as such. A note & call to contribute in case some structure file is incomplete would be nice though.

Thanks for your review !
I agree with your point of view but as a call for contribution, I think it's a good solution: the (future) contributors will only have to click on the "Help us improve" link to add content in empty templates, like the current link leading to GitHub.
Especially since we can consider another use case: specifying that a thesaurus is incomplete, even if it is not empty. What do you think about that?

**Comment by geekygirlsarah** [comment]
You know...  I don't like the draft flag mostly because I think it should just be researched when it's added. Also mistakes happen, but they can be corrected. 

But I DO like the idea that if there's pieces missing, a box shows up warning it's incomplete. There's been times we've updated the meta files and the language files haven't had the updates. So this would be where maybe I could see the incompleteness warning and then an option to populate the draft with the missing parts.

**Comment by geekygirlsarah** [comment]
So pondering on it a bit more... I do NOT like draft mode and think it should not be a thing.

However, I'm still ok with adding a thing to the UI at the top of the file saying that concept+language+version is incomplete and they can contribute. 

Also this is now VERY close to functionality of #605 and #628 (PR #629).  So let's make this issue JUST the UI part of it and the generator command, and the others can be on fixing the templates that add in the missing fields.

**Comment by ulyssear** [comment]
@geekygirlsarah The PR has been updated!
