### ISSUE TITLE
Feature: Add prettier 403, 404, and other error pages

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#67]
**Description:**
If there's a file not found error, or any other type of error, Python just crashes in a very ugly way. I'd like to make them prettier!

**Requirements:**
* Just a prettier version of the home page but with error text describing what happened
* It should be a general template that the error is passed into so the page can be reused easily

**Claiming This Issue:**
* Please leave a comment below indicating your interest. I can then assign it to you.
* If I don't see an update (comment, code, or PR), then I'll take your name off.
* You would always be welcome to reclaim it again.
* If you can't work on it, either leave a comment or remove yourself from the issue.
* If you have questions, please let me know!

**Comment by navjyot18** [comment]
can i work on this mam??

**Comment by geekygirlsarah** [comment]
Hey @navjyot18! Yeah, I'll give it to you. If I don't hear/see any updates in a week I may take you off of the issue. (You could always reclaim it again.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for the overview of things, and feel free to comment/email with any questions!

**Comment by geekygirlsarah** [comment]
@navjyot18 Hey, how's this issue coming along? I'll probably go ahead and unassign you but if you still want it, you can let me know and keep working on it.

**Comment by carl-evans** [comment]
Hi Sarah, I'm happy to take a look at this if you're interested?

**Comment by geekygirlsarah** [comment]
Hey @carl-evans! Yeah, I'd be happy to have you take it!

Look over the Contributing docs, and feel free to ask me any questions you have. I don't know that it would be helpful in this case, but docs.codethesaur.us is where documentation for the site is (there's not much on the Django site part yet.)

Thanks!

**Comment by geekygirlsarah** [comment]
Hi @carl-evans!

How is this coming along? Do you have any questions on it?

Thanks, and have a great day!

**Comment by geekygirlsarah** [comment]
@carl-evans It looks like you haven't worked on this, so I took your name off. If you want to take it back on, let me know.
