### ISSUE TITLE
Add GitHub Action to test the build of Docker containers

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#677]
# Description

It's possible to make changes to the `Dockerfile` or `docker-compose.yml` files and they might fail. This feature is to add a GitHub Action (either preexisting from elsewhere or make your own steps) to build it to make sure it works.

# Requirements

* Should be added somewhere in the workflows of CT, or it's own workflow

# Additional Notes

**Comment by flushthemoney** [comment]
I would like to work on this issue. But I'm just starting out with Open Source so I might take a bit longer, kindly assign this to me if it isn't too time sensitive. 

I'll reach out to you if I need any assistance.

**Comment by Siddharth9890** [comment]
@geekygirlsarah i can work on this as well

**Comment by geekygirlsarah** [comment]
Hey @flushthemoney you were first so I'll assign it to you. Let me know if you have any questions! I have an auto-unassign bot that may ping you if it takes a while, but just reply and it'll let you keep it longer. Or let me know if you want to give it up and we can pass it to @Siddharth9890.

**Comment by flushthemoney** [comment]
Sure, thank you.

**Comment by geekygirlsarah** [comment]
Since we haven't heard from @flushthemoney, if you wanted to work on it @Siddharth9890, you could. Let me know.

**Comment by ulyssear** [comment]
A pull request has been created for this issue (#693). Sorry if I didn't claim this before.
