### ISSUE TITLE
[Structure] Add language basics

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#679]
# Description

This issue is for adding a new structure for all languages that will let you compare a new aspect of a language. Ideally someone with many programming languages will help work on this.

This structure should be a way to describe language basics. This could be:

* Features of the language like whether it's compiled or interpreted, is static or dynamically typed, or is open source or not
* What the entry point of a program is (a main function? top of a file?)
* How do you add comments to a file?
* Is the language extensible (by internal or external libraries) and how you include those
* What's the most minimal program you can have?

Or other things. It should take some thought on all of the features that any programming language could have. Upon making this PR, expect it to have some revisions as people from various programming language backgrounds offer suggestions.

# Requirements

1. Look over the documentation at https://docs.codethesaur.us/thesaurus/add-new-structure/
2. Add a new file under `web/thesauruses/_meta` named whatever feels appropriate
3. Open up `web/thesauruses/meta_info.json` and add your new file to that file in the `structures` section.
4. Add in some categories, then add in the concepts under that
5. Feel free to use any `_meta` file as examples for how to do it
6. Make a PR and we can help test and review it

**Comment by sayantandasgupta** [comment]
Hi @geekygirlsarah I am an avid programmer and still learning about programming. May I work on this issue? I would really like to contribute to this project.

**Comment by geekygirlsarah** [comment]
This might not be a good first issue just because you have to understand a lot about the structure of programming languages. If you've taken a class on programming language design or have done a few different types, then this might be ok for you.

If not, there's 80+ other issues and probably at least one in a language you know.

Do you still want this issue, @sayantandasgupta ?

**Comment by sayantandasgupta** [comment]
Yes, I would like to give it a try. Nothing better to learn than by doing. Also, I would contribute in the following languages,

* Java
* Python
* C++

Will that be okay? I am supposed to go over the basics of what any programming language has to offer right?

**Comment by geekygirlsarah** [comment]
That does help, C++ and Java, for the purposes of this issue, are almost exactly the same, but Python helps diversify a bit.

You could look at https://en.wikipedia.org/wiki/Comparison_of_programming_languages for ideas too.

I'll go ahead and give it to you. Be sure to read the docs (link in issue) to understand it better.

**Comment by sayantandasgupta** [comment]
Thank you so much for this opportunity. I just have a few doubts that I need to clarify with you. Since I am supposed to add language basics of a particular programming language in the thesaurus. I have to create a separate JSON file let's say called language_basics.json inside the _meta folder where I am supposed to mention all the related concepts which are required for a language to work. Am I correct so far? This is what I inferred from going through the documentation

After doing this, I am supposed to go through each language and add the corresponding features am I correct?

**Comment by geekygirlsarah** [comment]
This is NOT for doing this for a specific language, but for defining what this would look like to be inside Code Thesaurus so that other languages COULD do this. Does that make sense?

So it's not:
Java: It's statically typed, object-oriented, functional, procedural, etc.

It is:
Any language could be:  statically or dynamically typed, could or could not be object-oriented, could or could not be functional, etc.

Does that help? You're defining what the structure for this looks like in CT.

**Comment by sayantandasgupta** [comment]
I think I am getting an idea. I would give it a hand and reply back to you.

**Comment by sayantandasgupta** [comment]
![image](https://github.com/codethesaurus/codethesaur.us/assets/61374798/b9cc7372-af8f-42f9-bc94-b3243aa17c89)

@geekygirlsarah I have made some progress with the structure of the basics. I wanted to get your opinion on whether I am on the right track on the basis of what we have discussed. Hence I have attached an image of the current structure which I have done as of now. I am structuring and adding more properties in the mean time

**Comment by geekygirlsarah** [comment]
First, yeah, that's a decent start. We can review it when it's done too.

Second, what might be easier is you can always push changes to your repo and just link it too (which is usually better than screenshots). At least I find the larger a file gets, the harder it is to share without just pointing to the file itself.

**Comment by sayantandasgupta** [comment]
https://github.com/sayantandasgupta/codethesaur.us/blob/issue-679-add-language-basics/web/thesauruses/_meta/language_basics.json

Hi @geekygirlsarah Based on our previous discussions, I have made the above updates.

**Comment by geekygirlsarah** [comment]
That's good. There's a few things I don't know that people will necessarily know (like what historical order of language) but it works. Can you add in some of the things on the issue above too? Then feel free to make a PR.

**Comment by geekygirlsarah** [comment]
This should still be assigned.
