### ISSUE TITLE
Add error reporting

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#686]
# Description

Errors just kind of happen and there's not a way to track them currently.

https://docs.djangoproject.com/en/4.2/howto/error-reporting/ lists Django's built in error reporting mechanisms.

Add one of those so Sarah's informed about errors.

# Requirements

1. Sarah's notified about errors somehow.

**Comment by cmoyer** [comment]
Depending on how many errors you get per day, setting up sendgrid as the default email backend and having it send you emails is pretty straight forward. Sendgrid's free plan covers 100 emails per day 

SENDGRID_API_KEY = api_key
EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
SERVER_EMAIL = 'sarahemail@gmail.com'

**Comment by geekygirlsarah** [comment]
Maybe... I'll keep it in mind. I was just thinking of sending to Code Thesaurus's (and my) email system already since I have all the DNS MX records pointed there and there's accounts that exist for this already. I'll look into it though!

**Comment by geekygirlsarah** [comment]
I'm still working on this.
