### ISSUE TITLE
Add/fix unit test(s) to check HTTP status codes for invalid lookups

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#691]
# Description

Bug #690 resulted from a invalid `language_name` / `friendly_language_name` mixup that would result in 500 server errors. The unit test that seem to check for invalid language/structures didn't catch this.

This issue should add new unit test(s) or fix the existing unit test(s) to make this more robust.

# Requirements

* Unit tests that check behind the scenes if invalid languages are looked up should be added/fixed
* Unit tests that check HTTP status codes (404, 500, others if needed) should be added/fixed for invalid lookups
* Probably should also add/fix unit tests for other scenarios too (other pages don't exist, malformed URLs, etc.)

# Additional Notes

This need to be tested locally to ensure they work:

* `python manage.py test` should run all unit tests
* `python manage.py validatelanginfofiles` should run tests on the language files
* `python manage.py validatemetainfofile` should run tests on the meta info file

While they'll be run when a pull request is made, making sure they run and pass locally first will speed things up.

**Comment by Jaivignesh-afk** [comment]
can you assign me this issue?

**Comment by sharktankful** [comment]
Hi I would love to work on this issue :)

**Comment by geekygirlsarah** [comment]
Hey @sharktankful, I missed your comment somehow. Feel free to take it!

**Comment by geekygirlsarah** [comment]
And let me know if you need any help.
