### ISSUE TITLE
[Language] Powershell

### ISSUE THREAD

**Issue by ulyssear** [codethesaurus/codethesaur.us#694]
# Language you would like added

Powershell

# Information on the language

Official documentation : https://learn.microsoft.com/powershell/ 

# Disclaimer

Please can i work on this issue ?

**Comment by geekygirlsarah** [comment]
This is a duplicate of #449. If you leave a comment on there I'll happily assign you!

**Comment by ulyssear** [comment]
I have started to do the first concepts : classes #696 and controls structures which will be done soon.

**Comment by geekygirlsarah** [comment]
Can you use #449 instead since this is a duplicate of that ticket?

**Comment by ulyssear** [comment]
Ok ! i will add the others concepts. I think it will better to have a task list to check the advancement on this issue.
