### ISSUE TITLE
Ambiguous number formatting within strings meta language file

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#717]
# Language

Meta language structure file

# Wrong Field(s)

There are fields to format integers and decimals. However, in C you can format those in multiple ways since you format by data type (including signed/unsigned, and float/double). This should probably be either renamed or added to. (Probably research which to do)

# Additional Information

Edit this in `web/thesauruses/_meta/strings.json`

# Disclaimer
If you would like to work on this issue, please comment here so that you are assigned.

**Comment by sarthakjalan05** [comment]
@geekygirlsarah assign me in the hacktoberfest tag

**Comment by geekygirlsarah** [comment]
I'll give it to you @sarthakjalan05 ! Feel free to look over the docs and ask me if you have any questions.

**Comment by sarthakjalan05** [comment]
@geekygirlsarah I have added a PR. Please check and do let me know if you need any further adjustments.
