### ISSUE TITLE
Bug: Reference lookups aren't logging in database

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#723]
# Expected Behavior

Any reference page lookup should be storing what was looked up in the web_lookupdata table in the database

# Actual Behavior

No lookup data is saving

# Steps to Reproduce the Problem

1. Lookup something (like Python version 3 functions)
1. Look inside the SQLite (locally) or Postgres (if you set it up) to see the row isn't in there

# Additional Info

Appears one hasn't been stored since Feb 2023. Maybe a migration could be added to catch this back up.

**Comment by Frederic-Chopin** [comment]
Hi Sarah, is it okay if I work on this? I just created a PR that resolves this issue:
https://github.com/codethesaurus/codethesaur.us/pull/724

I modified the `concepts` function in views.py to ensure that `store_lookup_info` is always called, even when there is only one language, which is the case for the reference lookup. I defaulted the second language to an empty string when there is only one language. I also tested locally and it works now, and web_lookupdata stores reference lookup correctly. If there is any question please let me know!

**Comment by geekygirlsarah** [comment]
Commenting to keep open for @Frederic-Chopin to finish some unit tests
