### ISSUE TITLE
Proposal to Add Kotlin "Classes" Concept

### ISSUE THREAD

**Issue by naeem4633** [codethesaurus/codethesaur.us#728]
# Language you would like added
Kotlin

# Information on the language
Kotlin is a modern, statically-typed programming language widely used for Android development and known for its expressive syntax and compatibility with Java.

- [Kotlin Official Documentation](https://kotlinlang.org/docs/home.html)

## Proposal
I propose to start adding Kotlin to the codethesaurus repository, beginning with the "Classes" concept. This will include providing example code snippets and explanations for classes in Kotlin.

### Example Snippet
**Classes in Kotlin:**
```kotlin
class Example {
    val property: String = "Hello, World!"
}

**Comment by geekygirlsarah** [comment]
I'm here for adding Kotlin! Would you like to add it or want me to leave it open for other contributors?

**Comment by naeem4633** [comment]
I would like to start adding myself.
I plan to start with the Classes section, allowing other developers to contribute additional sections if they wish. 
If needed, I can expand on the remaining sections later on.

**Comment by geekygirlsarah** [comment]
Sounds good to me! Docs are at https://docs.codethesaur.us, and let me know if you have any questions!

**Comment by naeem4633** [comment]
I've opened up the pull request, the classes part is done. I'll keep adding more parts in the future,
