### ISSUE TITLE
Bug: Compare/Reference pages show ID of concept, not human-friendly wording

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#73]
# Expected Behavior
The line at the top of the Compare or Reference pages shows something like "Comparing [language] and [language]'s data types"

# Actual Behavior
The line shows "Comparing [language] and [language]'s data_types"  (where data_types is the ID field)

# Steps to Reproduce the Problem

1. On the home page, click on two languages then Go
2. The incorrect line will be at the top
3. 

![image](https://user-images.githubusercontent.com/2601974/96505419-1677ba80-1224-11eb-884a-0c2f67f59008.png)

**Comment by mysticknits** [comment]
perhaps I can take this issue? 😬

**Comment by geekygirlsarah** [comment]
Consider it yours! Same deal... I'll let you have it for a week, then may take your name off. You can reclaim it later too. And ask any questions you might have!
