### ISSUE TITLE
Add CLIPS

### ISSUE THREAD

**Issue by mrryanjohnston** [codethesaurus/codethesaur.us#743]
# Language you would like added
[CLIPS](https://www.clipsrules.net/)

# Information on the language

CLIPS is a Rules-based programming language started in the mid 80s at NASA. It is still actively maintained today.

# Disclaimer
If you would like to work on this issue, please comment here so that you are assigned.

I would like to work on this issue :)

**Comment by geekygirlsarah** [comment]
Reassigning as it's stuck on a bug

**Comment by geekygirlsarah** [comment]
Reassigning (again) as it's stuck on a bug and I haven't had time to fix it yet
