### ISSUE TITLE
Tests report the wrong filename for invalid structures

### ISSUE THREAD

**Issue by cafce25** [codethesaurus/codethesaur.us#745]
When `foo` is defined as a structure in [`meta_info.json`] but the corresponding `_meta/foo.json` file is missing, the reported error message is quite confusing:

# Actual Behavior
```
Error:  `web/thesauruses/<language>` is not a valid concept filename
```

# Expected Behavior
something along the lines of 
```
Error:  `web/thesauruses/<language>/<version>/foo.json` is not a valid concept filename
```

# Steps to Reproduce the Problem

1. Add a new structure to [`meta_info.json`] (might not be necessary as the specific error is about the concept file itself).
2. Add a structure file for the new structure for any language.
3. **Don't** add a `_meta/foo.json`
4. Run `python manage.py validatemetainfofile`

# Additional Info
Here is an example of [a failed CI run with the described behavior](https://github.com/codethesaurus/codethesaur.us/actions/runs/10155413542/job/28110238636?pr=744)

[`meta_info.json`]: https://github.com/codethesaurus/codethesaur.us/blob/main/web/thesauruses/meta_info.json

**Comment by geekygirlsarah** [comment]
I'm impressed you're watching the CI/CD that closely! But this is valid. I can fix it if you're not already on it.
