### ISSUE TITLE
[Bug] For a language without a Pygments lexer, the program crashes

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#746]
# Expected Behavior

A language that may not have a style coloring lexer would either not use one or use some default of another language.

# Actual Behavior

CT crashes.

![image](https://github.com/user-attachments/assets/0b011a15-3327-454f-a2bc-1c528985a9bf)

# Steps to Reproduce the Problem

1. Run PR #744 locally
2. Do a reference of CLIPS with the Rules concept
3. Crash will happen

# Additional Info

I'm not sure what the right answer is or if there's a "default" lexer ([I didn't see one](https://pygments.org/languages/) but didn't look too hard). Maybe no formatting if there's no lexer?

**Comment by mrryanjohnston** [comment]
@geekygirlsarah you may be able to get away with using Common LISP since CLIPS has a LISP-like syntax
