### ISSUE TITLE
Consider looking at Exercism.io V3 Concepts

### ISSUE THREAD

**Issue by chriseyre2000** [codethesaurus/codethesaur.us#81]
# Use Exercism.io V3 as a data source
The Exercism.io project (https://github.com/exercism/v3) has a large amount of language concepts.

This may allow you to source a lot of languages quickly.

**Comment by geekygirlsarah** [comment]
Hi @chriseyre2000. Yeah I do know about Exercism and have looked at a lot of their repos and how they set up the system as a basis for some of what CT is doing. I do see they have a reference section but it seems quite varied between languages and what they provide and how they provide it. CT will need a bit more standardization around that, but perhaps could be used as a reference, along with language docs, to build out the data needed for the site.

Thanks for the suggestion!
