### ISSUE TITLE
Add JavaScript data types

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#87]
# Description

Data types for JavaScript aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/data_types.json` to the `web/thesauruses/javascript/` directory
* Edit the data_types.json file to accurately reflect the latest major version of JavaScript
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask @geekygirlsarah on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by dunk-boyz-12** [comment]
Hi! I would like to help with this and possibly some others, thanks!

**Comment by geekygirlsarah** [comment]
Hey @dunk-boyz-12! Yeah, I'll assign you to it. Make sure to check out the Contributing Guidelines and the docs. Feel free to ask any questions too!

If I don't see any updates in about a week, I'll take you off but you can always reclaim it too.

**Comment by dunk-boyz-12** [comment]
okay great, thank you!

**Comment by arpit-omprakash** [comment]
Hi @geekygirlsarah ! If this issue is still not resolved, can I work on this?

**Comment by geekygirlsarah** [comment]
Hey @aceking007! Yeah, I can pass this over to you. I revised the description a bit to hopefully be a bit more helpful. Let me know if you have any questions!

**Comment by arpit-omprakash** [comment]
Hi @geekygirlsarah! Thanks for assigning the issue to me. The revised description is more helpful than the previous one. However, I still have doubts about the `"name"` field. 
You don't want the `"name"` fields in the final PR right?

P.S. the link to contributing.md is malfunctioning in the description of the issue above. I found the doc, but you may consider fixing the link.

**Comment by geekygirlsarah** [comment]
The "names" are pulled from the meta language files (in /web/thesauruses/_meta/) so they're not needed in the individual language files. (they're ignored if left in.) We've generally left them out.

And I'll check on the contributing link, thanks! (it's on other issues from copy/paste so I'll make sure they're right too)

**Comment by arpit-omprakash** [comment]
Hi @geekygirlsarah ! I'm almost done with the changes. I will test them locally, push them, and make a PR by tomorrow. 

Meanwhile, is it okay if I ask to be assigned for other issues on this repo?

**Comment by geekygirlsarah** [comment]
> Meanwhile, is it okay if I ask to be assigned for other issues on this repo?

Yeah! If you're cool with it,I I'm cool with it. Just leave a comment on the one(s) you want to be tagged on. There's a few things that haven't been added to issues yet (like strings in all languages) which you can make if you want.

**Comment by arpit-omprakash** [comment]
Hey @geekygirlsarah I'm not sure what to fill in the "what type of PR is this question" for this issue. Any suggestions?  
The question is as follows:

## 📝 What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

**Comment by geekygirlsarah** [comment]
Oh I usually just do "feature". I think I'm eventually taking those checkmarks off.
