### ISSUE TITLE
Add PHP data types

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#88]
# Description

The PHP language is presently not on Code Thesaurus. I would love to see this added and the data types concept added to CT.

# Requirements

* Copy `web/thesauruses/_meta/data_types.json` to a `web/thesauruses/php/` directory
* Edit the data_types.json file to accurately reflect PHP and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://github.com/codethesaurus/docs/blob/main/docs/thesaurus/index.md](https://github.com/codethesaurus/docs/blob/main/docs/thesaurus/index.md) for information on more specifics of implementing this.

**Comment by binarygary** [comment]
@geekygirlsarah And can I call dibs here too?

**Comment by geekygirlsarah** [comment]
Consider this yours too! 

(And I hear you know my friend Allison, so cool!)

**Comment by binarygary** [comment]
Allison is awesome!
