### ISSUE TITLE
Add Swift data types

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#89]
# Description

Data Types for Swift aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/data_types.json` to the right Swift directory in `web/thesauruses/`
* Edit the data_types.json file to accurately reflect the latest major version of Swift
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](https://github.com/codethesaurus/codethesaur.us/blob/main/CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask [@geekygirlsarah](https://twitter.com/geekygirlsarah) on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by gildedgardenia** [comment]
Hey! I think I can help with this one too!

**Comment by geekygirlsarah** [comment]
Sweet! I'll let you have it. Again, let me know if you have any questions!
