### ISSUE TITLE
Add C++ functions

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#93]
# Description

The functions in C++ are presently not on Code Thesaurus. I would love to see this added.

# Requirements

* Copy `web/thesauruses/_meta/functions.json` to a `web/thesauruses/cplusplus/` directory
* Edit the functions.json file to accurately reflect C++ and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on more specifics of implementing this.

**Comment by andrewCodeDev** [comment]
I'd be happy to take a look at this for you! Sounds like an interesting project.

**Comment by geekygirlsarah** [comment]
Hey @andrewCodeDev! I'll pass it over to you then!

Docs are now over at https://docs.codethesaur.us, and feel free to ask any questions you have!

**Comment by geekygirlsarah** [comment]
@andrewCodeDev Since I haven't heard from you in a few weeks, I'm removing you from this issue. If you started on this, or want to still work on this issue, let me know and I can re-assign you to it.
