### ISSUE TITLE
[Java] Add functions

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#96]
# Description

Functions for Java aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/functions.json` to the `web/thesauruses/java/` directory
* Edit the functions.json file to accurately reflect the latest major version of Java
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask @geekygirlsarah on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by enisaras** [comment]
I can help with this too!

**Comment by geekygirlsarah** [comment]
Consider this yours too!

And same drill...  if you need help, just let me know!

**Comment by geekygirlsarah** [comment]
Hi @enisaras!

How is this coming along? Do you have any questions on it?

Thanks, and have a great day!

**Comment by enisaras** [comment]
Hey @geekygirlsarah;
I definitely did not forget about this, I will get it done. I have been busy doing my Java assignment(ironic, I know) and studying for my midterms.

**Comment by geekygirlsarah** [comment]
That's fine! I was doing some spring cleaning and just making sure people were still interested in issues they had. (I was a student once... I understand!)

**Comment by geekygirlsarah** [comment]
@enisaras Since I haven't heard from you in a few weeks, I'm removing you from this issue. If you started on this, or want to still work on this issue, let me know and I can re-assign you to it.

**Comment by Swastik2000** [comment]
I want to work on this issue. I have just completed my advanced JAVA course. That's why I think I can help you with this issue.

**Comment by geekygirlsarah** [comment]
I'll pass it along to you then. Let me know if you have any questions, and look at docs.codethesaur.us for some instructions.

**Comment by Swastik2000** [comment]
@geekygirlsarah 
I'm new to Docker, and the page on my localhost runs fine after making the docker container. 
The problem is when I make a change of code to the function.json file after transferring from `web/thesauruses/_meta/functions.json` to  `web/thesauruses/java/directory` 
and refresh, the site doesn't change. 
I've seen people saying to rebuild the image so I stoped the container by pressing **ctrl+c** then used 
`docker build -t ct-image .`  to build it again and then I used `docker start ct-container` and then `docker attach ct-container`
 
Still, the site remains unchanged I'm not sure what that means or if there is another way. I want to use docker only instead of manual installation.

**Comment by geekygirlsarah** [comment]
Last time I checked, Docker should pull in code changes automatically, no need to rebuild it. So I'm thinking that's not the problem.

Do you have a branch somewhere I could look at to see what's happening? You could also make a draft pull request too and I could look at that.

**Comment by geekygirlsarah** [comment]
Hi @Swastik2000, what's the latest status on this? Is this working? Do you need any help?

**Comment by Swastik2000** [comment]
Hi, @geekygirlsarah sorry for the delay. I will create a pr within this week. Since few days my health condition was not that good due to which there was no progress in this issue.

**Comment by Aryan-Srivastava** [comment]
hey @Swastik2000  , can I take up this issue if you aren't working

**Comment by Swastik2000** [comment]
@Aryan-Srivastava I have completed 80% of the issue. I will create a PR for this issue by tomorrow evening

**Comment by Aryan-Srivastava** [comment]
@Swastik2000 okay, go ahead 👍

**Comment by geekygirlsarah** [comment]
Hey @Swastik2000, how is this coming along? I haven't seen any updates and it's been several weeks now. If you still want the issue, let me know otherwise I'll probably unassign you. And if you have any questions, let me know too!

**Comment by geekygirlsarah** [comment]
I'm unassigning people, but I don't want to unassign if you have 80+% of it done @Swastik2000. I'm reaching out again. Let me know if you still want to work on it!

**Comment by arrkyn** [comment]
Hey! I'd like to work on this

**Comment by geekygirlsarah** [comment]
Sweet! I'll assign you. Let me know if you have any questions!

**Comment by geekygirlsarah** [comment]
Did you still want this, @kodykodec?

**Comment by arrkyn** [comment]
Yes please

**Comment by geekygirlsarah** [comment]
Commenting to leave open due to draft PR

**Comment by tpenn** [comment]
I'm claiming this issue and putting in a PR now.

**Comment by geekygirlsarah** [comment]
Cool, assigned you and will review shortly! Congrats on being the first issue claimed of Hacktoberfest!
