### ISSUE TITLE
Add JavaScript functions

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#97]
# Description

The functions in JavaScript are presently not on Code Thesaurus. I would love to see this added.

# Requirements

* Copy `web/thesauruses/_meta/functions.json` to a `web/thesauruses/javascript/` directory
* Edit the functions.json file to accurately reflect JavaScript and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on more specifics of implementing this.

**Comment by nicholasbus** [comment]
Hi, I would be interested in working on this. Thanks.

**Comment by geekygirlsarah** [comment]
@nicholasbus Thanks for your patience and I would love for you to take this on! Be sure to check out the Contributing.md file as well as the documentation which is now over at docs.codethesaur.us.

I'll leave you on for about a week and take you off if I don't see any updates. If that happens, you're always welcome to grab it again later.
