### ISSUE TITLE
Add Objective-C functions

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#98]
# Description

Functions for Objective-C aren't presently on Code Thesaurus. This issue is to add that concept to the system.

# Requirements

* Copy `web/thesauruses/_meta/functions.json` to the `web/thesauruses/objectivec/` directory
* Edit the functions.json file to accurately reflect the latest major version of Objective-C
* Delete the `"name":` fields before your PR
* Add in `"comment":` if you wish to explain something in the code
* Add in `"not-implemented": "true"` if the concept doesn't exist in the language. You can then leave `"code":` blank.

# Claiming This Issue

Please leave a comment below so I can assign you to it. This is to prevent multiple people from working on the same issue. 

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://docs.codethesaur.us/thesaurus/](https://docs.codethesaur.us/thesaurus/) for information on how Code Thesaurus works and how to add to the thesauruses.

# Need Help?

Leave a comment on here with your question, or feel free to ask @geekygirlsarah on Twitter. You can also email coreteam@codethesaur.us too.

# Thanks!

We really value and appreciate the additions people make to Code Thesaurus, no matter how large or small. So thank you for taking the time to work on this!

**Comment by gildedgardenia** [comment]
Hey @geekygirlsarah! I can return back to Objective-C land and take this issue if that is helpful to you!

**Comment by geekygirlsarah** [comment]
It's more if it's something you want to do! I'll assign you. Same drill as before, let me know if you have any questions!

**Comment by gildedgardenia** [comment]
Thanks Sarah! I fell behind at work but I am happy to work on this tonight!

**Comment by geekygirlsarah** [comment]
No rush! (Though minor rush if you want a Hacktoberfest shirt)
