### ISSUE TITLE
Add PHP functions

### ISSUE THREAD

**Issue by geekygirlsarah** [codethesaurus/codethesaur.us#99]
# Description

The functions in PHP are presently not on Code Thesaurus. I would love to see this added.

# Requirements

* Copy `web/thesauruses/_meta/functions.json` to a `web/thesauruses/php/` directory
* Edit the functions.json file to accurately reflect PHP and the latest major version of it.

# Additional Notes

Please leave comments on this issue to ask questions or to claim the issue as yours. I'll keep it yours for a week then remove you in case someone else wants to work on it. (You can always reclaim it.)

Check out [CONTRIBUTING.md](CONTRIBUTING.md) for more information on how to contribute. 

Check out [https://github.com/codethesaurus/docs/blob/main/docs/thesaurus/index.md](https://github.com/codethesaurus/docs/blob/main/docs/thesaurus/index.md) for information on more specifics of implementing this.

**Comment by binarygary** [comment]
@geekygirlsarah Can I call dibs on this one too?

**Comment by geekygirlsarah** [comment]
Yep, consider it yours too!
